/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-01-30 08:40:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class jQueryForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>First jQuery Example</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js\">\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\">\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("						// Styling changes\r\n");
      out.write("						$(\"p\").css(\"background-color\", \"Wheat\");\r\n");
      out.write("						$(\"p\").css(\"font-size\", \"18px\");\r\n");
      out.write("\r\n");
      out.write("						// Hover effect\r\n");
      out.write("						$(\"p\").hover(function() {$(this).css(\"color\", \"black\");\r\n");
      out.write("						}, function() {\r\n");
      out.write("							$(this).css(\"color\", \"red\");\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("						// Click effect to fade out paragraph\r\n");
      out.write("						$(\"p\").click(function() {\r\n");
      out.write("							$(this).fadeOut(1000);\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("						// Slide toggle effect for hidden text\r\n");
      out.write("						$(\"#toggleText\").click(function() {\r\n");
      out.write("							$(\".hiddenText\").slideToggle();\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("						// Fade in effect\r\n");
      out.write("						$(\"#fadeInBtn\").click(function() {\r\n");
      out.write("							$(\".fadeInText\").fadeIn(1000);\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("						// Fade out effect\r\n");
      out.write("						$(\"#fadeOutBtn\").click(function() {\r\n");
      out.write("							$(\".fadeOutText\").fadeOut(1000);\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("						// Animate effect (move an element)\r\n");
      out.write("						$(\"#animateBtn\").click(function() {\r\n");
      out.write("							$(\".animateText\").animate({\r\n");
      out.write("								left : '250px',\r\n");
      out.write("								opacity : '0.5',\r\n");
      out.write("								height : 'toggle'\r\n");
      out.write("							}, 1500);\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("						// Toggle class on a button click\r\n");
      out.write("						$(\"#toggleClassBtn\").click(function() {\r\n");
      out.write("							$(\"p\").toggleClass(\"highlighted\");\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("						// Append new content to a div\r\n");
      out.write("						$(\"#appendBtn\").click(function() {$(\"#newContent\").append(\r\n");
      out.write("															\"<p>This is some dynamically appended content!</p>\");\r\n");
      out.write("										});\r\n");
      out.write("\r\n");
      out.write("						// Prepend new content to a div\r\n");
      out.write("						$(\"#prependBtn\").click(function() {$(\"#newContent\").prepend(\r\n");
      out.write("															\"<p>This content is prepended at the top!</p>\");\r\n");
      out.write("										});\r\n");
      out.write("\r\n");
      out.write("						// Toggle visibility of an element\r\n");
      out.write("						$(\"#toggleVisibilityBtn\").click(function() {$(\".toggleVisibilityText\").toggle();\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("						// Show element\r\n");
      out.write("						$(\"#showBtn\").click(function() {$(\".showText\").show();\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("						// Hide element\r\n");
      out.write("						$(\"#hideBtn\").click(function() {$(\".hideText\").hide();\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("						// Delay effect\r\n");
      out.write("						$(\"#delayBtn\").click(function() {$(\".delayText\").delay(1000).fadeIn(1000);\r\n");
      out.write("						});\r\n");
      out.write("					});\r\n");
      out.write("\r\n");
      out.write("	$(function() {$(\"p\").css(\"color\", \"black\");\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<p>\r\n");
      out.write("			<b>The $ sign is nothing but an identifier of jQuery() function.\r\n");
      out.write("				Instead of writing jQuery we simply write $ which is the same as\r\n");
      out.write("				jQuery() function. A $ with a selector specifies that it is a jQuery\r\n");
      out.write("				selector.</b>\r\n");
      out.write("		</p>\r\n");
      out.write("		<p>\r\n");
      out.write("			<b>jQuery is a lightweight, \"write less, do more\", JavaScript\r\n");
      out.write("				library. The purpose of jQuery is to make it much easier to use\r\n");
      out.write("				JavaScript on your website.</b>\r\n");
      out.write("		</p>\r\n");
      out.write("		<p>\r\n");
      out.write("			<b>The name was chosen because the library was designed to make\r\n");
      out.write("				it easier to work with JavaScript.</b>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<!-- Button to toggle text visibility -->\r\n");
      out.write("		<button id=\"toggleText\" class=\"btn btn-primary\">Toggle Text</button>\r\n");
      out.write("		<p class=\"hiddenText\" style=\"display: none;\">\r\n");
      out.write("			<b>This text is hidden and can be toggled by clicking the button\r\n");
      out.write("				above!</b>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<!-- Buttons to demonstrate various effects -->\r\n");
      out.write("		<button id=\"fadeInBtn\" class=\"btn btn-success\">Fade In Text</button>\r\n");
      out.write("		<p class=\"fadeInText\" style=\"display: none;\">\r\n");
      out.write("			<b>This text will fade in!</b>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<button id=\"fadeOutBtn\" class=\"btn btn-danger\">Fade Out Text</button>\r\n");
      out.write("		<p class=\"fadeOutText\">\r\n");
      out.write("			<b>This text will fade out when the button is clicked.</b>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<button id=\"animateBtn\" class=\"btn btn-warning\">Animate Text</button>\r\n");
      out.write("		<p class=\"animateText\" style=\"position: relative; left: 0px;\">\r\n");
      out.write("			<b>This text will animate and move across the screen!</b>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<button id=\"toggleClassBtn\" class=\"btn btn-info\">Toggle Class</button>\r\n");
      out.write("		<p class=\"highlighted\">\r\n");
      out.write("			<b>This paragraph will change class when the button is clicked.</b>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<button id=\"appendBtn\" class=\"btn btn-secondary\">Append Text</button>\r\n");
      out.write("		<div id=\"newContent\">\r\n");
      out.write("			<p>This is existing content.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<button id=\"prependBtn\" class=\"btn btn-secondary\">Prepend\r\n");
      out.write("			Text</button>\r\n");
      out.write("		<div id=\"newContent\"></div>\r\n");
      out.write("\r\n");
      out.write("		<button id=\"toggleVisibilityBtn\" class=\"btn btn-dark\">Toggle\r\n");
      out.write("			Visibility</button>\r\n");
      out.write("		<p class=\"toggleVisibilityText\" style=\"display: none;\">\r\n");
      out.write("			<b>This text will toggle visibility.</b>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<button id=\"showBtn\" class=\"btn btn-light\">Show Text</button>\r\n");
      out.write("		<p class=\"showText\" style=\"display: none;\">\r\n");
      out.write("			<b>This text will be shown when you click the button.</b>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<button id=\"hideBtn\" class=\"btn btn-dark\">Hide Text</button>\r\n");
      out.write("		<p class=\"hideText\">\r\n");
      out.write("			<b>This text will be hidden when you click the button.</b>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<button id=\"delayBtn\" class=\"btn btn-primary\">Delay Fade In</button>\r\n");
      out.write("		<p class=\"delayText\" style=\"display: none;\">\r\n");
      out.write("			<b>This text will fade in with a delay.</b>\r\n");
      out.write("		</p>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
