/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-02-24 09:35:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sampleDisplay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"stylesheet.css\">\r\n");
      out.write("<style>\r\n");
      out.write("a.nav-link {\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-item {\r\n");
      out.write("	padding-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<nav class=\"navbar navbar-expand-xxl bg-info  \">\r\n");
      out.write("\r\n");
      out.write("		<ul class=\"navbar-nav  \">\r\n");
      out.write("			<li><a class=\"navbar-brands\" href=\"dashboard.jsp\"><img\r\n");
      out.write("					src=\"kbcnum.jpg\" alt=\"logo\" style=\"width: 60px\"\r\n");
      out.write("					class=\"rounded-pill\"></a></li>\r\n");
      out.write("			<li class=\"nav-item \"><a class=\"nav-link \" href=\"dashboard.jsp\">Home</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li class=\"nav-item \"><a class=\"nav-link\" href=\"login.jsp\">login</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">Registaration</a></li>\r\n");
      out.write("			<li class=\"nav-item dropdown\"><a\r\n");
      out.write("				class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\"\r\n");
      out.write("				data-bs-toggle=\"dropdown\">More</a>\r\n");
      out.write("				<ul class=\"dropdown-menu\">\r\n");
      out.write("					<li><a class=\"dropdown-item Active\" href=\"ViewStudent\">view</a></li>\r\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"#\">Log out</a></li>\r\n");
      out.write("				</ul></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<h2 id=\"heading\">\r\n");
      out.write("		<img src=\"kbcnum.jpg\" alt=\"kbcnum logo\">Kavayitri Bahinabai\r\n");
      out.write("		Chaudhari North Maharashtra University, Jalgaon.\r\n");
      out.write("	</h2>\r\n");
      out.write("	<h3>Registaration Form</h3>\r\n");
      out.write("\r\n");
      out.write("	<form action=\"RegisterServlet\" method=\"post\">\r\n");
      out.write("		<table class=\"center\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><label for=\"fName\">First Name:</label></td>\r\n");
      out.write("				<td><input type=\"text\" id=\"fName\" name=\"fname\"\r\n");
      out.write("					placeholder=\"Enter your first name\"\r\n");
      out.write("					oninput=\"validatefirstname(this)\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><span id=\"errorfirstname\" style=\"color: red\"></span></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><label for=\"lName\">Last Name:</label></td>\r\n");
      out.write("				<td><input type=\"text\" id=\"lName\" name=\"lname\"\r\n");
      out.write("					placeholder=\"Enter your last name\" oninput=\"validatelastname(this)\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><span id=\"errorlastname\" style=\"color: red\"></span></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><label for=\"mobile\">Mobile No:</label></td>\r\n");
      out.write("				<td><input type=\"text\" id=\"mobile\" name=\"mobile\"\r\n");
      out.write("					placeholder=\"Enter the Mobile no.\" oninput=\"validateMobile(this)\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><span id=\"errorMobile\" style=\"color: red\"></span></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><label for=\"email\">Email Id:</label></td>\r\n");
      out.write("				<td><input type=\"email\" id=\"email\" name=\"email\"\r\n");
      out.write("					placeholder=\"Enter your email id\" oninput=\"validateEmail(this)\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><span id=\"errorEmail\" style=\"color: red\"></span></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><label for=\"address\">Address:</label></td>\r\n");
      out.write("				<td><textarea name=\"address\" id=\"address\" rows=\"5\" col=\"30\"></textarea>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><label for=\"gender\">Gender:</label></td>\r\n");
      out.write("				<td><input type=\"radio\" id=\"male\" value=\"male\" name=\"gender\">Male\r\n");
      out.write("					<input type=\"radio\" id=\"female\" value=\"female\" name=\"gender\">Female</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><label for=\"DOB\">DOB:</label></td>\r\n");
      out.write("				<td><input type=\"Date\" id=\"DOB\" name=\"DOB\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><label for=\"branch\">Choose Branch:</label></td>\r\n");
      out.write("				<td><select id=\"branch\" name=\"branch\">\r\n");
      out.write("						<option value=\"BSC\">BSC</option>\r\n");
      out.write("						<option value=\"BCA\">BCA</option>\r\n");
      out.write("						<option value=\"MSC\" selected>MSC</option>\r\n");
      out.write("						<option value=\"MCA\">MCA</option>\r\n");
      out.write("				</select></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><label for=\"specialization\">Specialization:</label></td>\r\n");
      out.write("				<td><input type=\"checkbox\" id=\"cs\" name=\"specialization\"\r\n");
      out.write("					value=\"Computer Science\">Computer Science <input\r\n");
      out.write("					type=\"checkbox\" id=\"it\" name=\"specialization\"\r\n");
      out.write("					value=\"Information Technology\">Information Technology</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("		<div>\r\n");
      out.write("			<input type=\"submit\" id=\"submit\" name=\"submit\"onsubmit=\"validatesubmit(event)\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"errorsubmit\" style=\"color: red\"></div>\r\n");
      out.write("	</form>\r\n");
      out.write("	<div class=\"fixed-bottom bg-info p-3 text-white\">\r\n");
      out.write("		<p>© 2022 BY KAVAYITRI BAHINABAI CHAUDHARI NORTH MAHARASHTRA\r\n");
      out.write("			UNIVERSITY, JALGAON</p>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function validatefirstname(input) {\r\n");
      out.write("			console.log(input.value);\r\n");
      out.write("			var regex = /^[a-zA-Z]+$/;\r\n");
      out.write("			var errorfirstname = document.getElementById('errorfirstname');\r\n");
      out.write("			if (!regex.test(input.value)) {\r\n");
      out.write("				errorfirstname.innerHTML = \"Please enter alphabet only\";\r\n");
      out.write("			} else {\r\n");
      out.write("				errorfirstname.innerHTML = \"\";\r\n");
      out.write("				return input.value;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function validatelastname(input) {\r\n");
      out.write("			console.log(input.value);\r\n");
      out.write("			var regex = /^[a-zA-Z]+$/;\r\n");
      out.write("			var errorlastname = document.getElementById('errorlastname');\r\n");
      out.write("			if (!regex.test(input.value)) {\r\n");
      out.write("				errorlastname.innerHTML = \"Please enter alphabet only\";\r\n");
      out.write("			} else {\r\n");
      out.write("				errorlastname.innerHTML = \"\";\r\n");
      out.write("				return input.value;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function validateMobile(input) {\r\n");
      out.write("			console.log(input.value);\r\n");
      out.write("			var regex = /^\\d{10}$/;\r\n");
      out.write("			var errorMobile = document.getElementById('errorMobile');\r\n");
      out.write("			if (!regex.test(input.value)) {\r\n");
      out.write("				errorMobile.innerHTML = \"Please enter 10 digit number\";\r\n");
      out.write("			} else {\r\n");
      out.write("				errorMobile.innerHTML = \"\";\r\n");
      out.write("				return input.value;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function validateEmail(input) {\r\n");
      out.write("			console.log(input.value);\r\n");
      out.write("			var regex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\r\n");
      out.write("			var errorEmail = document.getElementById('errorEmail');\r\n");
      out.write("			if (!regex.test(input.value)) {\r\n");
      out.write("				errorEmail.textContent = \"Please enter correct email id\";\r\n");
      out.write("			} else {\r\n");
      out.write("				errorEmail.textContent = \"\";\r\n");
      out.write("				return input.value;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function validatesubmit(event) {\r\n");
      out.write("			validatefirstname(document.getElementById('fName'));\r\n");
      out.write("			validatelastname(document.getElementById('lName'));\r\n");
      out.write("			validateMobile(document.getElementById('mobile'));\r\n");
      out.write("			validateEmail(document.getElementById('email'));\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
