/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-02-03 06:59:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class javascriptFunctionsjsp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>JavaScript Methods in JSP</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("        // 1. DOM Manipulation\r\n");
      out.write("        function changeText() {\r\n");
      out.write("            var element = document.getElementById(\"demoText\");\r\n");
      out.write("            element.innerHTML = \"The text has been changed!\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 2. Event Handling\r\n");
      out.write("        function showAlert() {\r\n");
      out.write("            alert(\"Hello! You clicked the button.\");\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 3. Adding a new element dynamically\r\n");
      out.write("        function addElement() {\r\n");
      out.write("            var newElement = document.createElement(\"div\");\r\n");
      out.write("            newElement.innerHTML = \"This is a dynamically added element.\";\r\n");
      out.write("            document.body.appendChild(newElement);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 4. Fetch API (AJAX) example\r\n");
      out.write("        function fetchData() {\r\n");
      out.write("            fetch('https://jsonplaceholder.typicode.com/posts/1')\r\n");
      out.write("                .then(response => response.json())\r\n");
      out.write("                .then(data => {\r\n");
      out.write("                    document.getElementById(\"ajaxContent\").innerHTML = `\r\n");
      out.write("                        <h3>Fetched Data:</h3>\r\n");
      out.write("                        <p><strong>Title:</strong> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                        <p><strong>Body:</strong> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.body}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                    `;\r\n");
      out.write("                })\r\n");
      out.write("                .catch(error => console.log('Error fetching data:', error));\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 5. LocalStorage example\r\n");
      out.write("        function saveData() {\r\n");
      out.write("            localStorage.setItem('username', document.getElementById('username').value);\r\n");
      out.write("            alert('Data saved in LocalStorage!');\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function retrieveData() {\r\n");
      out.write("            var username = localStorage.getItem('username');\r\n");
      out.write("            alert('Saved username: ' + username);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 6. Validate input field\r\n");
      out.write("        function validateInput() {\r\n");
      out.write("            var inputValue = document.getElementById(\"userInput\").value;\r\n");
      out.write("            if(inputValue === \"\") {\r\n");
      out.write("                alert(\"Input field cannot be empty!\");\r\n");
      out.write("            } else {\r\n");
      out.write("                alert(\"You entered: \" + inputValue);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h1>\r\n");
      out.write("			<i>Using JavaScript Methods in JSP</i>\r\n");
      out.write("		</h1>\r\n");
      out.write("\r\n");
      out.write("		<p id=\"demoText\">\r\n");
      out.write("			<b>JavaScript is a scripting language used to develop web pages.</b>\r\n");
      out.write("		</p>\r\n");
      out.write("		<button onclick=\"changeText()\">Change Text</button>\r\n");
      out.write("		<br> <br>\r\n");
      out.write("\r\n");
      out.write("		<button onclick=\"showAlert()\">Show Alert</button>\r\n");
      out.write("		<br> <br>\r\n");
      out.write("\r\n");
      out.write("		<button onclick=\"addElement()\">Add New Element</button>\r\n");
      out.write("		<br> <br>\r\n");
      out.write("\r\n");
      out.write("		<button onclick=\"fetchData()\">Fetch Data via AJAX</button>\r\n");
      out.write("		<div id=\"ajaxContent\"></div>\r\n");
      out.write("		<br> <br> <input type=\"text\" id=\"username\"\r\n");
      out.write("			placeholder=\"Enter Username\">\r\n");
      out.write("		<button onclick=\"saveData()\">Save Username to LocalStorage</button>\r\n");
      out.write("		<br> <br>\r\n");
      out.write("		<button onclick=\"retrieveData()\">Retrieve Saved Username</button>\r\n");
      out.write("		<br> <br> <input type=\"text\" id=\"userInput\"\r\n");
      out.write("			placeholder=\"Enter something\">\r\n");
      out.write("		<button onclick=\"validateInput()\">Validate Input</button>\r\n");
      out.write("		<br> <br>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
