/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-01-29 07:14:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class multipleForms_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#regForm {\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("	margin: 100px auto;\r\n");
      out.write("	font-family: Raleway;\r\n");
      out.write("	padding: 40px;\r\n");
      out.write("	width: 70%;\r\n");
      out.write("	min-width: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	font-size: 17px;\r\n");
      out.write("	font-family: Raleway;\r\n");
      out.write("	border: 1px solid #aaaaaa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Mark input boxes that gets an error on validation: */\r\n");
      out.write("input.invalid {\r\n");
      out.write("	background-color: #ffdddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Hide all steps by default: */\r\n");
      out.write(".tab {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("	background-color: #04AA6D;\r\n");
      out.write("	color: #ffffff;\r\n");
      out.write("	border: none;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	font-size: 17px;\r\n");
      out.write("	font-family: Raleway;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:hover {\r\n");
      out.write("	opacity: 0.8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#prevBtn {\r\n");
      out.write("	background-color: #bbbbbb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Make circles that indicate the steps of the form: */\r\n");
      out.write(".step {\r\n");
      out.write("	height: 15px;\r\n");
      out.write("	width: 15px;\r\n");
      out.write("	margin: 0 2px;\r\n");
      out.write("	background-color: #bbbbbb;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	opacity: 0.5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".step.active {\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Mark the steps that are finished and valid: */\r\n");
      out.write(".step.finish {\r\n");
      out.write("	background-color: #04AA6D;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<form id=\"regForm\" action=\"/action_page.php\">\r\n");
      out.write("		<h1>Register:</h1>\r\n");
      out.write("		<!-- One \"tab\" for each step in the form: -->\r\n");
      out.write("		<div class=\"tab\">\r\n");
      out.write("			Name:\r\n");
      out.write("			<p>\r\n");
      out.write("				<input placeholder=\"First name...\" oninput=\"this.className = ''\"\r\n");
      out.write("					name=\"fname\">\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<input placeholder=\"Last name...\" oninput=\"this.className = ''\"\r\n");
      out.write("					name=\"lname\">\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"tab\">\r\n");
      out.write("			Contact Info:\r\n");
      out.write("			<p>\r\n");
      out.write("				<input placeholder=\"E-mail...\" oninput=\"this.className = ''\"\r\n");
      out.write("					name=\"email\">\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<input placeholder=\"Phone...\" oninput=\"this.className = ''\"\r\n");
      out.write("					name=\"phone\">\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"tab\">\r\n");
      out.write("			Birthday:\r\n");
      out.write("			<p>\r\n");
      out.write("				<input placeholder=\"dd\" oninput=\"this.className = ''\" name=\"dd\">\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<input placeholder=\"mm\" oninput=\"this.className = ''\" name=\"nn\">\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<input placeholder=\"yyyy\" oninput=\"this.className = ''\" name=\"yyyy\">\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"tab\">\r\n");
      out.write("			Login Info:\r\n");
      out.write("			<p>\r\n");
      out.write("				<input placeholder=\"Username...\" oninput=\"this.className = ''\"\r\n");
      out.write("					name=\"uname\">\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<input placeholder=\"Password...\" oninput=\"this.className = ''\"\r\n");
      out.write("					name=\"pword\" type=\"password\">\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div style=\"overflow: auto;\">\r\n");
      out.write("			<div style=\"float: right;\">\r\n");
      out.write("				<button type=\"button\" id=\"prevBtn\" onclick=\"nextPrev(-1)\">Previous</button>\r\n");
      out.write("				<button type=\"button\" id=\"nextBtn\" onclick=\"nextPrev(1)\">Next</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Circles which indicates the steps of the form: -->\r\n");
      out.write("		<div style=\"text-align: center; margin-top: 40px;\">\r\n");
      out.write("			<span class=\"step\"></span> <span class=\"step\"></span> <span\r\n");
      out.write("				class=\"step\"></span> <span class=\"step\"></span>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		var currentTab = 0; // Current tab is set to be the first tab (0)\r\n");
      out.write("		showTab(currentTab); // Display the current tab\r\n");
      out.write("\r\n");
      out.write("		function showTab(n) {\r\n");
      out.write("			// This function will display the specified tab of the form...\r\n");
      out.write("			var x = document.getElementsByClassName(\"tab\");\r\n");
      out.write("			x[n].style.display = \"block\";\r\n");
      out.write("			//... and fix the Previous/Next buttons:\r\n");
      out.write("			if (n == 0) {\r\n");
      out.write("				document.getElementById(\"prevBtn\").style.display = \"none\";\r\n");
      out.write("			} else {\r\n");
      out.write("				document.getElementById(\"prevBtn\").style.display = \"inline\";\r\n");
      out.write("			}\r\n");
      out.write("			if (n == (x.length - 1)) {\r\n");
      out.write("				document.getElementById(\"nextBtn\").innerHTML = \"Submit\";\r\n");
      out.write("			} else {\r\n");
      out.write("				document.getElementById(\"nextBtn\").innerHTML = \"Next\";\r\n");
      out.write("			}\r\n");
      out.write("			//... and run a function that will display the correct step indicator:\r\n");
      out.write("			fixStepIndicator(n)\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function nextPrev(n) {\r\n");
      out.write("			// This function will figure out which tab to display\r\n");
      out.write("			var x = document.getElementsByClassName(\"tab\");\r\n");
      out.write("			// Exit the function if any field in the current tab is invalid:\r\n");
      out.write("			if (n == 1 && !validateForm())\r\n");
      out.write("				return false;\r\n");
      out.write("			// Hide the current tab:\r\n");
      out.write("			x[currentTab].style.display = \"none\";\r\n");
      out.write("			// Increase or decrease the current tab by 1:\r\n");
      out.write("			currentTab = currentTab + n;\r\n");
      out.write("			// if you have reached the end of the form...\r\n");
      out.write("			if (currentTab >= x.length) {\r\n");
      out.write("				// ... the form gets submitted:\r\n");
      out.write("				document.getElementById(\"regForm\").submit();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			// Otherwise, display the correct tab:\r\n");
      out.write("			showTab(currentTab);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function validateForm() {\r\n");
      out.write("			// This function deals with validation of the form fields\r\n");
      out.write("			var x, y, i, valid = true;\r\n");
      out.write("			x = document.getElementsByClassName(\"tab\");\r\n");
      out.write("			y = x[currentTab].getElementsByTagName(\"input\");\r\n");
      out.write("			// A loop that checks every input field in the current tab:\r\n");
      out.write("			for (i = 0; i < y.length; i++) {\r\n");
      out.write("				// If a field is empty...\r\n");
      out.write("				if (y[i].value == \"\") {\r\n");
      out.write("					// add an \"invalid\" class to the field:\r\n");
      out.write("					y[i].className += \" invalid\";\r\n");
      out.write("					// and set the current valid status to false\r\n");
      out.write("					valid = false;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			// If the valid status is true, mark the step as finished and valid:\r\n");
      out.write("			if (valid) {\r\n");
      out.write("				document.getElementsByClassName(\"step\")[currentTab].className += \" finish\";\r\n");
      out.write("			}\r\n");
      out.write("			return valid; // return the valid status\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function fixStepIndicator(n) {\r\n");
      out.write("			// This function removes the \"active\" class of all steps...\r\n");
      out.write("			var i, x = document.getElementsByClassName(\"step\");\r\n");
      out.write("			for (i = 0; i < x.length; i++) {\r\n");
      out.write("				x[i].className = x[i].className.replace(\" active\", \"\");\r\n");
      out.write("			}\r\n");
      out.write("			//... and adds the \"active\" class on the current step:\r\n");
      out.write("			x[n].className += \" active\";\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write(">\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
