/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-03-05 06:08:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sign_002din_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\n");
      out.write("=========================================================\n");
      out.write("* Material Dashboard 3 - v3.2.0\n");
      out.write("=========================================================\n");
      out.write("\n");
      out.write("* Product Page: https://www.creative-tim.com/product/material-dashboard\n");
      out.write("* Copyright 2024 Creative Tim (https://www.creative-tim.com)\n");
      out.write("* Licensed under MIT (https://www.creative-tim.com/license)\n");
      out.write("* Coded by Creative Tim\n");
      out.write("\n");
      out.write("=========================================================\n");
      out.write("\n");
      out.write("* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n");
      out.write("-->\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\" />\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("  <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"../assets/img/apple-icon.png\">\n");
      out.write("  <link rel=\"icon\" type=\"image/png\" href=\"../assets/img/favicon.png\">\n");
      out.write("  <title>\n");
      out.write("    Material Dashboard 3 by Creative Tim\n");
      out.write("  </title>\n");
      out.write("  <!--     Fonts and icons     -->\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700,900\" />\n");
      out.write("  <!-- Nucleo Icons -->\n");
      out.write("  <link href=\"../assets/css/nucleo-icons.css\" rel=\"stylesheet\" />\n");
      out.write("  <link href=\"../assets/css/nucleo-svg.css\" rel=\"stylesheet\" />\n");
      out.write("  <!-- Font Awesome Icons -->\n");
      out.write("  <script src=\"https://kit.fontawesome.com/42d5adcbca.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("  <!-- Material Icons -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0\" />\n");
      out.write("  <!-- CSS Files -->\n");
      out.write("  <link id=\"pagestyle\" href=\"../assets/css/material-dashboard.css?v=3.2.0\" rel=\"stylesheet\" />\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"bg-gray-200\">\n");
      out.write("  <div class=\"container position-sticky z-index-sticky top-0\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("      <div class=\"col-12\">\n");
      out.write("        <!-- Navbar -->\n");
      out.write("        <nav class=\"navbar navbar-expand-lg blur border-radius-xl top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4\">\n");
      out.write("          <div class=\"container-fluid ps-2 pe-0\">\n");
      out.write("            <a class=\"navbar-brand font-weight-bolder ms-lg-0 ms-3 \" href=\"../pages/dashboard.html\">\n");
      out.write("              Material Dashboard 3\n");
      out.write("            </a>\n");
      out.write("            <button class=\"navbar-toggler shadow-none ms-2\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navigation\" aria-controls=\"navigation\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("              <span class=\"navbar-toggler-icon mt-2\">\n");
      out.write("                <span class=\"navbar-toggler-bar bar1\"></span>\n");
      out.write("                <span class=\"navbar-toggler-bar bar2\"></span>\n");
      out.write("                <span class=\"navbar-toggler-bar bar3\"></span>\n");
      out.write("              </span>\n");
      out.write("            </button>\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navigation\">\n");
      out.write("              <ul class=\"navbar-nav mx-auto\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link d-flex align-items-center me-2 active\" aria-current=\"page\" href=\"../pages/dashboard.html\">\n");
      out.write("                    <i class=\"fa fa-chart-pie opacity-6 text-dark me-1\"></i>\n");
      out.write("                    Dashboard\n");
      out.write("                  </a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link me-2\" href=\"../pages/profile.html\">\n");
      out.write("                    <i class=\"fa fa-user opacity-6 text-dark me-1\"></i>\n");
      out.write("                    Profile\n");
      out.write("                  </a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link me-2\" href=\"../pages/sign-up.html\">\n");
      out.write("                    <i class=\"fas fa-user-circle opacity-6 text-dark me-1\"></i>\n");
      out.write("                    Sign Up\n");
      out.write("                  </a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link me-2\" href=\"../pages/sign-in.html\">\n");
      out.write("                    <i class=\"fas fa-key opacity-6 text-dark me-1\"></i>\n");
      out.write("                    Sign In\n");
      out.write("                  </a>\n");
      out.write("                </li>\n");
      out.write("              </ul>\n");
      out.write("              <ul class=\"navbar-nav d-lg-flex d-none\">\n");
      out.write("                <li class=\"nav-item d-flex align-items-center\">\n");
      out.write("                  <a class=\"btn btn-outline-primary btn-sm mb-0 me-2\" target=\"_blank\" href=\"https://www.creative-tim.com/builder?ref=navbar-material-dashboard\">Online Builder</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a href=\"https://www.creative-tim.com/product/material-dashboard\" class=\"btn btn-sm mb-0 me-1 bg-gradient-dark\">Free download</a>\n");
      out.write("                </li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </nav>\n");
      out.write("        <!-- End Navbar -->\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <main class=\"main-content  mt-0\">\n");
      out.write("    <div class=\"page-header align-items-start min-vh-100\" style=\"background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80');\">\n");
      out.write("      <span class=\"mask bg-gradient-dark opacity-6\"></span>\n");
      out.write("      <div class=\"container my-auto\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-lg-4 col-md-8 col-12 mx-auto\">\n");
      out.write("            <div class=\"card z-index-0 fadeIn3 fadeInBottom\">\n");
      out.write("              <div class=\"card-header p-0 position-relative mt-n4 mx-3 z-index-2\">\n");
      out.write("                <div class=\"bg-gradient-dark shadow-dark border-radius-lg py-3 pe-1\">\n");
      out.write("                  <h4 class=\"text-white font-weight-bolder text-center mt-2 mb-0\">Sign in</h4>\n");
      out.write("                  <div class=\"row mt-3\">\n");
      out.write("                    <div class=\"col-2 text-center ms-auto\">\n");
      out.write("                      <a class=\"btn btn-link px-3\" href=\"javascript:;\">\n");
      out.write("                        <i class=\"fa fa-facebook text-white text-lg\"></i>\n");
      out.write("                      </a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-2 text-center px-1\">\n");
      out.write("                      <a class=\"btn btn-link px-3\" href=\"javascript:;\">\n");
      out.write("                        <i class=\"fa fa-github text-white text-lg\"></i>\n");
      out.write("                      </a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-2 text-center me-auto\">\n");
      out.write("                      <a class=\"btn btn-link px-3\" href=\"javascript:;\">\n");
      out.write("                        <i class=\"fa fa-google text-white text-lg\"></i>\n");
      out.write("                      </a>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"card-body\">\n");
      out.write("                <form role=\"form\" class=\"text-start\">\n");
      out.write("                  <div class=\"input-group input-group-outline my-3\">\n");
      out.write("                    <label class=\"form-label\">Email</label>\n");
      out.write("                    <input type=\"email\" class=\"form-control\">\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"input-group input-group-outline mb-3\">\n");
      out.write("                    <label class=\"form-label\">Password</label>\n");
      out.write("                    <input type=\"password\" class=\"form-control\">\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"form-check form-switch d-flex align-items-center mb-3\">\n");
      out.write("                    <input class=\"form-check-input\" type=\"checkbox\" id=\"rememberMe\" checked>\n");
      out.write("                    <label class=\"form-check-label mb-0 ms-3\" for=\"rememberMe\">Remember me</label>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"text-center\">\n");
      out.write("                    <button type=\"button\" class=\"btn bg-gradient-dark w-100 my-4 mb-2\">Sign in</button>\n");
      out.write("                  </div>\n");
      out.write("                  <p class=\"mt-4 text-sm text-center\">\n");
      out.write("                    Don't have an account?\n");
      out.write("                    <a href=\"../pages/sign-up.html\" class=\"text-primary text-gradient font-weight-bold\">Sign up</a>\n");
      out.write("                  </p>\n");
      out.write("                </form>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <footer class=\"footer position-absolute bottom-2 py-2 w-100\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <div class=\"row align-items-center justify-content-lg-between\">\n");
      out.write("            <div class=\"col-12 col-md-6 my-auto\">\n");
      out.write("              <div class=\"copyright text-center text-sm text-white text-lg-start\">\n");
      out.write("                Â© <script>\n");
      out.write("                  document.write(new Date().getFullYear())\n");
      out.write("                </script>,\n");
      out.write("                made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by\n");
      out.write("                <a href=\"https://www.creative-tim.com\" class=\"font-weight-bold text-white\" target=\"_blank\">Creative Tim</a>\n");
      out.write("                for a better web.\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-12 col-md-6\">\n");
      out.write("              <ul class=\"nav nav-footer justify-content-center justify-content-lg-end\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a href=\"https://www.creative-tim.com\" class=\"nav-link text-white\" target=\"_blank\">Creative Tim</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a href=\"https://www.creative-tim.com/presentation\" class=\"nav-link text-white\" target=\"_blank\">About Us</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a href=\"https://www.creative-tim.com/blog\" class=\"nav-link text-white\" target=\"_blank\">Blog</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a href=\"https://www.creative-tim.com/license\" class=\"nav-link pe-0 text-white\" target=\"_blank\">License</a>\n");
      out.write("                </li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </footer>\n");
      out.write("    </div>\n");
      out.write("  </main>\n");
      out.write("  <!--   Core JS Files   -->\n");
      out.write("  <script src=\"../assets/js/core/popper.min.js\"></script>\n");
      out.write("  <script src=\"../assets/js/core/bootstrap.min.js\"></script>\n");
      out.write("  <script src=\"../assets/js/plugins/perfect-scrollbar.min.js\"></script>\n");
      out.write("  <script src=\"../assets/js/plugins/smooth-scrollbar.min.js\"></script>\n");
      out.write("  <script>\n");
      out.write("    var win = navigator.platform.indexOf('Win') > -1;\n");
      out.write("    if (win && document.querySelector('#sidenav-scrollbar')) {\n");
      out.write("      var options = {\n");
      out.write("        damping: '0.5'\n");
      out.write("      }\n");
      out.write("      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);\n");
      out.write("    }\n");
      out.write("  </script>\n");
      out.write("  <!-- Github buttons -->\n");
      out.write("  <script async defer src=\"https://buttons.github.io/buttons.js\"></script>\n");
      out.write("  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->\n");
      out.write("  <script src=\"../assets/js/material-dashboard.min.js?v=3.2.0\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
