/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-08 16:05:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import School.trn.trn_students.StudentsDTO;
import School.Mst.Mst_subjects.SubjectsDTO;
import School.Mst.Mst_examTypes.ExamTypesDTO;

public final class MarksIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1751952690829L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("School.trn.trn_students.StudentsDTO");
    _jspx_imports_classes.add("School.Mst.Mst_subjects.SubjectsDTO");
    _jspx_imports_classes.add("School.Mst.Mst_examTypes.ExamTypesDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Add Student Marks</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- nav.jsp -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\">School System</a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#mainNav\"\r\n");
      out.write("            aria-controls=\"mainNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"mainNav\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"mastersDropdown\" role=\"button\"\r\n");
      out.write("             data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Masters</a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"mastersDropdown\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"class\">Classes</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"course\">Courses</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"department\">Departments</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"designation\">Designations</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"examTypes\">Exam Types</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"feeTypes\">Fee Types</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"subjects\">Subjects</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"userRoles\">User Roles</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"transactionsDropdown\" role=\"button\"\r\n");
      out.write("             data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Transactions</a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"mastersDropdown\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"marksList\">Marks</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"teachersList\">Teachers</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"studentList\">Students</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("		\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("\r\n");
      out.write("    <h2 class=\"mb-4\">Add Marks</h2>\r\n");
      out.write("\r\n");
      out.write("    <form action=\"marks\" method=\"post\" class=\"row g-3\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <label class=\"form-label\">Student</label>\r\n");
      out.write("            <select name=\"student_id\" class=\"form-select\" required>\r\n");
      out.write("                <option value=\"\">-- Select Student --</option>\r\n");
      out.write("                ");

                    List<StudentsDTO> students = (List<StudentsDTO>) request.getAttribute("students");
                    if (students != null && !students.isEmpty()) {
                        for (StudentsDTO stu : students) {
                
      out.write("\r\n");
      out.write("                <option value=\"");
      out.print( stu.getStudent_id() );
      out.write('"');
      out.write('>');
      out.print( stu.getStudent_name() );
      out.write("</option>\r\n");
      out.write("                ");

                        }
                    }
                
      out.write("\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <label class=\"form-label\">Subject</label>\r\n");
      out.write("            <select name=\"subject_id\" class=\"form-select\" required>\r\n");
      out.write("                <option value=\"\">-- Select Subject --</option>\r\n");
      out.write("                ");

                    List<SubjectsDTO> subjects = (List<SubjectsDTO>) request.getAttribute("subjects");
                    if (subjects != null && !subjects.isEmpty()) {
                        for (SubjectsDTO subj : subjects) {
                
      out.write("\r\n");
      out.write("                <option value=\"");
      out.print( subj.getSubject_id() );
      out.write('"');
      out.write('>');
      out.print( subj.getSubject_name() );
      out.write("</option>\r\n");
      out.write("                ");

                        }
                    }
                
      out.write("\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <label class=\"form-label\">Exam Type</label>\r\n");
      out.write("            <select name=\"exam_type_id\" class=\"form-select\" required>\r\n");
      out.write("                <option value=\"\">-- Select Exam --</option>\r\n");
      out.write("                ");

                    List<ExamTypesDTO> exams = (List<ExamTypesDTO>) request.getAttribute("examTypes");
                    if (exams != null && !exams.isEmpty()) {
                        for (ExamTypesDTO ex : exams) {
                
      out.write("\r\n");
      out.write("                <option value=\"");
      out.print( ex.getExam_type_id() );
      out.write('"');
      out.write('>');
      out.print( ex.getExam_name() );
      out.write("</option>\r\n");
      out.write("                ");

                        }
                    }
                
      out.write("\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <label class=\"form-label\">Marks</label>\r\n");
      out.write("            <input type=\"number\" name=\"marks\" step=\"0.01\" min=\"0\" class=\"form-control\" required />\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-success\">Add Marks</button>\r\n");
      out.write("            <a href=\"marksList\" class=\"btn btn-secondary\">View All Marks</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
