/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-16 16:16:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import School.trn.trn_students.StudentsDTO;
import School.Mst.Mst_Classes.ClassesDTO;
import School.Mst.Mst_Courses.CoursesDTO;

public final class StudentsUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("School.trn.trn_students.StudentsDTO");
    _jspx_imports_classes.add("School.Mst.Mst_Classes.ClassesDTO");
    _jspx_imports_classes.add("School.Mst.Mst_Courses.CoursesDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Edit Student</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("    body {\r\n");
      out.write("        background-image: url('Images/img5.jpg');\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        background-repeat: no-repeat;\r\n");
      out.write("        background-attachment: fixed;\r\n");
      out.write("        background-position: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container {\r\n");
      out.write("        background-color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container mt-5 bg-dark mb-5\">\r\n");
      out.write("<div class=\"container mt-3 bg-dark text-white p-4 rounded shadow\">\r\n");
      out.write("    <h2 class=\"text-center mb-4\">Edit Student</h2>\r\n");
      out.write("    ");

      StudentsDTO student = (StudentsDTO) request.getAttribute("student");
      List<ClassesDTO> classList = (List<ClassesDTO>) request.getAttribute("classes");
      List<CoursesDTO> courseList = (List<CoursesDTO>) request.getAttribute("courses");
    
      out.write("\r\n");
      out.write("    <form action=\"updateStudent\" method=\"post\" name=\"studentUpdate\" onsubmit=\"return validateUpdate();\">\r\n");
      out.write("      <!-- include hidden PK -->\r\n");
      out.write("      <input type=\"hidden\" name=\"student_id\" value=\"");
      out.print( student.getStudent_id() );
      out.write("\"/>\r\n");
      out.write("\r\n");
      out.write("      <!-- Name -->\r\n");
      out.write("      <div class=\"mb-3\">\r\n");
      out.write("        <label for=\"student_name\" class=\"form-label\">Student Name</label>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" id=\"student_name\" name=\"name\"\r\n");
      out.write("               value=\"");
      out.print( student.getStudent_name() );
      out.write("\" >\r\n");
      out.write("               <span id=\"nameError\" style=\"color: red\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- DOB -->\r\n");
      out.write("      <div class=\"mb-3\">\r\n");
      out.write("        <label for=\"dob\" class=\"form-label\">Date of Birth</label>\r\n");
      out.write("        <input type=\"date\" class=\"form-control\" id=\"dob\" name=\"dob\"\r\n");
      out.write("               value=\"");
      out.print( student.getDob() );
      out.write("\" required>\r\n");
      out.write("               <span id=\"dobError\" style=\"color: black\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Gender -->\r\n");
      out.write("      <div class=\"mb-3\">\r\n");
      out.write("        <label class=\"form-label\">Gender</label><br>\r\n");
      out.write("        <div class=\"form-check form-check-inline\">\r\n");
      out.write("          <input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"male\" value=\"Male\"\r\n");
      out.write("            ");
      out.print( "Male".equals(student.getGender()) ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("          <label class=\"form-check-label\" for=\"male\">Male</label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-check form-check-inline\">\r\n");
      out.write("          <input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"female\" value=\"Female\"\r\n");
      out.write("            ");
      out.print( "Female".equals(student.getGender()) ? "checked" : "" );
      out.write(">\r\n");
      out.write("          <label class=\"form-check-label\" for=\"female\">Female</label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <span id=\"genderError\" style=\"color: black\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Contact -->\r\n");
      out.write("      <div class=\"mb-3\">\r\n");
      out.write("        <label for=\"contact\" class=\"form-label\">Contact</label>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" id=\"contact\" name=\"contact\"\r\n");
      out.write("               value=\"");
      out.print( student.getContact() );
      out.write("\" required>\r\n");
      out.write("               <span id=\"contactError\" style=\"color: black\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Class -->\r\n");
      out.write("      <div class=\"mb-3\">\r\n");
      out.write("    <label for=\"class_id\" class=\"form-label\">Select Class</label>\r\n");
      out.write("    <select class=\"form-select\" id=\"class_id\" name=\"class_id\" required>\r\n");
      out.write("        <option value=\"\">-- Select Class --</option>\r\n");
      out.write("        ");

            if (classList != null) {
                for (ClassesDTO cls : classList) {
                    String sel = cls.getClassId() == student.getClass_id() ? "selected" : "";
        
      out.write("\r\n");
      out.write("            <option value=\"");
      out.print( cls.getClassId() );
      out.write('"');
      out.write(' ');
      out.print( sel );
      out.write('>');
      out.print( cls.getClassName() );
      out.write("</option>\r\n");
      out.write("        ");

                }
            }
        
      out.write("\r\n");
      out.write("    </select>\r\n");
      out.write("    <span id=\"classError\" style=\"color: black\"></span>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Course -->\r\n");
      out.write("      <div class=\"mb-3\">\r\n");
      out.write("    <label for=\"course_id\" class=\"form-label\">Select Course</label>\r\n");
      out.write("    <select class=\"form-select\" id=\"course_id\" name=\"course_id\" required>\r\n");
      out.write("        <option value=\"\">-- Select Course --</option>\r\n");
      out.write("        ");

            if (courseList != null) {
                for (CoursesDTO co : courseList) {
                    String selCo = co.getCourse_id() == student.getCourse_id() ? "selected" : "";
        
      out.write("\r\n");
      out.write("            <option value=\"");
      out.print( co.getCourse_id() );
      out.write('"');
      out.write(' ');
      out.print( selCo );
      out.write('>');
      out.print( co.getCourse_name() );
      out.write("</option>\r\n");
      out.write("        ");

                }
            }
        
      out.write("\r\n");
      out.write("    </select>\r\n");
      out.write("    <span id=\"courseError\" style=\"color: black\"></span>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Actions -->\r\n");
      out.write("      <div class=\"d-grid gap-2\">\r\n");
      out.write("        <button type=\"submit\"  class=\"btn btn-primary\">Save Changes</button>\r\n");
      out.write("        <a href=\"studentList\" class=\"btn btn-secondary\">Cancel</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\" integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function validateUpdate(){\r\n");
      out.write("		$(\"#nameError\").html('');\r\n");
      out.write("		$(\"#dobError\").html('');\r\n");
      out.write("		$(\"#genderError\").html('');\r\n");
      out.write("		$(\"#contactError\").html('');\r\n");
      out.write("		$(\"#classError\").html('');\r\n");
      out.write("		$(\"#courseError\").html('');\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		var isValid = true;\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		var name = $('input[name=\"name\"]').val().trim();\r\n");
      out.write("		console.log('Name: '+name);\r\n");
      out.write("		\r\n");
      out.write("		var dob = $('#dob').val().trim();\r\n");
      out.write("		console.log('DOB: '+dob);\r\n");
      out.write("		\r\n");
      out.write("		var gender = $('input[name=\"gender\"]:checked').val();\r\n");
      out.write("		console.log('Gender: '+gender);\r\n");
      out.write("		\r\n");
      out.write("		var contact = $('#contact').val().trim();\r\n");
      out.write("		console.log('Contact: '+contact);\r\n");
      out.write("		\r\n");
      out.write("		var classes = $('#class_id').val().trim();\r\n");
      out.write("		console.log('Class: '+classes);\r\n");
      out.write("		\r\n");
      out.write("		var courses = $(\"#course_id\").val().trim();\r\n");
      out.write("		console.log('Course: '+courses);\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		if(name === ''){\r\n");
      out.write("			$(\"#nameError\").html(\"Name is required.\");\r\n");
      out.write("	        isValid = false;\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("		if(dob === ''){\r\n");
      out.write("			$(\"#dobError\").html(\"Please pick dob.\");\r\n");
      out.write("			isValid = false;\r\n");
      out.write("		}\r\n");
      out.write("	    \r\n");
      out.write("		if (!gender) {\r\n");
      out.write("		    $(\"#genderError\").html(\"Please select gender.\");\r\n");
      out.write("		    isValid = false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	    if (contact === '' || contact.length !== 10 || isNaN(contact)){\r\n");
      out.write("	    	$(\"#contactError\").html(\"Please enter a valid 10-digit contact.\");\r\n");
      out.write("	    	isValid = false;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    if(classes === ''){\r\n");
      out.write("	    	$(\"#classError\").html(\"Please select class.\");\r\n");
      out.write("	    	isValid = false;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    if(courses === ''){\r\n");
      out.write("	    	$(\"#courseError\").html(\"please select course.\");\r\n");
      out.write("	    	isValid = false;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("		\r\n");
      out.write("	    return isValid;\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
