/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-09-01 05:52:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import School.trn.trn_students.StudentsDTO;
import School.Mst.Mst_Classes.ClassesDTO;
import School.Mst.Mst_Courses.CoursesDTO;

public final class Students_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/session_expired.jsp", Long.valueOf(1755837901527L));
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1756016672277L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("School.trn.trn_students.StudentsDTO");
    _jspx_imports_classes.add("School.Mst.Mst_Classes.ClassesDTO");
    _jspx_imports_classes.add("School.Mst.Mst_Courses.CoursesDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Student Directory</title>\r\n");
      out.write("   <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("   <style>\r\n");
      out.write("    body {\r\n");
      out.write("        background-image: url('Images/imgg.jpg');\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        background-repeat: no-repeat;\r\n");
      out.write("        background-attachment: fixed;\r\n");
      out.write("        background-position: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container {\r\n");
      out.write("        background-color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    .table-transparent {\r\n");
      out.write("  color: #fff !important;   /* make all text white */\r\n");
      out.write("  background-color: transparent !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-transparent thead, \r\n");
      out.write(".table-transparent tbody, \r\n");
      out.write(".table-transparent th, \r\n");
      out.write(".table-transparent td, \r\n");
      out.write(".table-transparent tr {\r\n");
      out.write("  background-color: transparent !important;\r\n");
      out.write("  color: #fff !important;   /* force white text */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-transparent.table-striped > tbody > tr:nth-of-type(odd) {\r\n");
      out.write("  --bs-table-accent-bg: rgba(255,255,255,0.05) !important; /* faint stripe */\r\n");
      out.write("  color: #fff !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container mt-5 text-light\"\r\n");
      out.write("style=\"background-color: rgba(0,0,0,0.5); border-radius: 12px; padding:20px;\">\r\n");
      out.write('\r');
      out.write('\n');

String logedInUser = session.getAttribute("logedInUser") == null ? "" : (String) session.getAttribute("logedInUser");
if(logedInUser.equals("")){
	response.sendRedirect("HomePage.jsp");
}

      out.write(' ');
      out.write("\r\n");
      out.write("<!-- nav.jsp -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark py-4\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"welcome.jsp\">\r\n");
      out.write("    	<img src=\"Images/School2.png\" alt=\"Logo\" width=\"30\" height=\"30\" class=\"d-inline-block align-text-top me-2\">\r\n");
      out.write("    	<img src=\"Images/logo (1).png\" alt=\"Logo\" width=\"200\" height=\"30\" class=\"d-inline-block align-text-top me-2\">\r\n");
      out.write("  \r\n");
      out.write("    </a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#mainNav\"\r\n");
      out.write("            aria-controls=\"mainNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"mainNav\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle fs-6 text-light\" href=\"#\" id=\"mastersDropdown\" role=\"button\"\r\n");
      out.write("             data-bs-toggle=\"dropdown\" aria-expanded=\"false\" >Masters</a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"mastersDropdown\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"class\">Classes</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"course\">Courses</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"department\">Departments</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"designation\">Designations</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"examTypes\">Exam Types</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"feeTypes\">Fee Types</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"subjects\">Subjects</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"userRoles\">User Roles</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle fs-6 text-light\" href=\"#\" id=\"transactionsDropdown\" role=\"button\"\r\n");
      out.write("             data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Transactions</a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"mastersDropdown\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"marksList\">Marks</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"Teachers.jsp\">Teachers</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"Students.jsp\">Students</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"logout.jsp\">Logout</a>\r\n");
      out.write("        </li>\r\n");
      out.write("		\r\n");
      out.write("      </ul>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Notification bell -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");

	
	int rows = request.getParameter("rows")==null?10:Integer.parseInt(request.getParameter("rows"));
	
      out.write("                                               \r\n");
      out.write("\r\n");
      out.write("    <h2 class=\"mb-4\">Students List</h2>\r\n");
      out.write("    \r\n");
      out.write("   <form action=\"students\" name=\"searchform\" method=\"get\" class=\"row gx-3 gy-2 align-items-center mb-4\">\r\n");
      out.write("    <input type=\"hidden\" name=\"cpage\" value=\"1\"/>\r\n");
      out.write("\r\n");
      out.write("    <!-- Search Box --> \r\n");
      out.write("    <div class=\"col-auto\">\r\n");
      out.write("        <input type=\"text\" name=\"query\" class=\"form-control\" placeholder=\"Enter search term\" id=\"query\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Class Dropdown -->\r\n");
      out.write("    <div class=\"col-auto\">\r\n");
      out.write("        <select class=\"form-select\" name=\"class_id\" id=\"searchClassId\">\r\n");
      out.write("            <option value=\"\">-- Select Class --</option> \r\n");
      out.write("            \r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Course Dropdown -->\r\n");
      out.write("    <div class=\"col-auto\">\r\n");
      out.write("        <select class=\"form-select\" name=\"course_id\" id=\"searchCourseId\">\r\n");
      out.write("            <option value=\"\">-- Select Course --</option>\r\n");
      out.write("            \r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-auto\">\r\n");
      out.write("       <input type=\"number\" value=\"");
      out.print(rows );
      out.write("\" name=\"rows\" id=\"rows\" class=\"form-control\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-auto\">\r\n");
      out.write("    	<select class=\"form-select\" name=\"sort_column\">\r\n");
      out.write("    		<option value=\"student_id\" ");
      out.print( "student_id".equals(request.getAttribute("sortColumn"))? "selected" :"" );
      out.write(">Sort by ID</option>\r\n");
      out.write("    		<option value=\"student_name\" ");
      out.print( "student_name".equals(request.getAttribute("sortColumn"))? "selected" :"" );
      out.write(">Sort by Name</option>\r\n");
      out.write("    		<option value=\"dob\" ");
      out.print( "dob".equals(request.getAttribute("sortColumn"))? "selected" :"" );
      out.write(">Sort by DOB</option>\r\n");
      out.write("    		<option value=\"gender\" ");
      out.print( "gender".equals(request.getAttribute("sortColumn"))? "selected" :"" );
      out.write(">Sort by Gender</option>\r\n");
      out.write("    		<option value=\"contact\" ");
      out.print( "contact".equals(request.getAttribute("sortColumn"))? "selected" :"" );
      out.write(">Sort by Contact</option>\r\n");
      out.write("    		<option value=\"class_name\" ");
      out.print( "class_name".equals(request.getAttribute("sortColumn"))? "selected" :"" );
      out.write(">Sort by Class</option>\r\n");
      out.write("    		<option value=\"course_name\" ");
      out.print( "course_name".equals(request.getAttribute("sortColumn"))? "selected" :"" );
      out.write(">Sort by Course</option>\r\n");
      out.write("    	</select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-auto\">\r\n");
      out.write("        <button type=button class=\"btn btn-primary\" onclick=\"loadStudentList()\">Search</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("    <table class=\"table table-bordered table-hover text-center table-striped table-dark table-transparent\">\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>ID</th>\r\n");
      out.write("                <th>Name</th>\r\n");
      out.write("                <th>DOB</th>\r\n");
      out.write("                <th>Gender</th>\r\n");
      out.write("                <th>Contact</th>\r\n");
      out.write("                <th>Class</th>\r\n");
      out.write("                <th>Course</th>\r\n");
      out.write("                <th>Actions</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody id=\"studentTblBody\">\r\n");
      out.write("        \r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("   \r\n");
      out.write("    <div class=\"mt-3\">        \r\n");
      out.write("         <button type=\"button\" class=\"btn btn-warning\" data-bs-toggle=\"modal\" data-bs-target=\"#addStudentModal\">\r\n");
      out.write(" 			 Add New Student\r\n");
      out.write("		</button>\r\n");
      out.write("		<div class=\"modal fade\" id=\"addStudentModal\" tabindex=\"-1\" aria-labelledby=\"addStudentModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("    <div class=\"modal-content text-dark\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"addStudentModalLabel\">Add New Teacher</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <form action=\"students\" method=\"post\" name=\"studentForm\" id=\"contactForm\">\r\n");
      out.write("        \r\n");
      out.write("        <input type=\"hidden\" name=\"student_id\" id=\"student_id\">\r\n");
      out.write("        \r\n");
      out.write("        <input type=\"hidden\" name=\"action\" id=\"actionID\"/>\r\n");
      out.write("            <!-- Student Name -->\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"student_name\" class=\"form-label\">Student Name</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"student_name\" name=\"name\" required>\r\n");
      out.write("                <span id=\"nameError\" style=\"color: grey\"></span>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Date of Birth -->\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"dob\" class=\"form-label\">Date of Birth</label>\r\n");
      out.write("                <input type=\"date\" class=\"form-control\" id=\"dob\" name=\"dob\" required>\r\n");
      out.write("                <span id=\"dobError\" style=\"color: grey\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Gender -->\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label class=\"form-label\">Gender</label><br>\r\n");
      out.write("                <div class=\"form-check form-check-inline\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"gender\" value=\"Male\" id=\"male\" required>\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"male\">Male</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check form-check-inline\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"gender\" value=\"Female\" id=\"female\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"female\">Female</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span id=\"genderError\" style=\"color: grey\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Contact -->\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"contact\" class=\"form-label\">Contact</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"contact\" name=\"contact\" onblur=\"doCheckContact(this.value)\" required maxlength=\"10\">\r\n");
      out.write("                <span id=\"contactError\" style=\"color: grey\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Class dropdown -->\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"class_id\" class=\"form-label\">Select Class</label>\r\n");
      out.write("                <select class=\"form-select\" id=\"class_id\" name=\"class_id\" required>\r\n");
      out.write("                    <option value=\"\">-- Select Class --</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <span id=\"classError\" style=\"color: grey\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Course dropdown -->\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"course_id\" class=\"form-label\">Select Course</label>\r\n");
      out.write("                <select class=\"form-select\" id=\"course_id\" name=\"course_id\" required>\r\n");
      out.write("                    <option value=\"\">-- Select Course --</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <span id=\"courseError\" style=\"color: grey\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Buttons -->\r\n");
      out.write("            <div class=\"d-grid gap-2\">\r\n");
      out.write("                <button type=\"button\" onclick=\"validateInfo()\"  class=\"btn btn-primary\" id=\"addbtnID\">Add Student</button>\r\n");
      out.write("                <a href=\"studentList\" class=\"btn btn-secondary\">Cancel</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\" integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("	 console.log('page load');\r\n");
      out.write("	 loadStudentList();\r\n");
      out.write("	 loadClassesList();\r\n");
      out.write("	 loadCoursesList();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function loadStudentList(){\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: 'studentList',\r\n");
      out.write("		type: 'GET',\r\n");
      out.write("		data: {\r\n");
      out.write("			query: $(\"#query\").val(),\r\n");
      out.write("            class_id: $(\"#searchClassId\").val(),\r\n");
      out.write("            course_id: $(\"#searchCourseId\").val(),\r\n");
      out.write("            rows: $(\"#rows\").val(),\r\n");
      out.write("            sort_column: $(\"select[name='sort_column']\").val(),\r\n");
      out.write("            cpage: 1\r\n");
      out.write("		},\r\n");
      out.write("		success: function(data){\r\n");
      out.write("			console.log(data);\r\n");
      out.write("			var students = eval(data);\r\n");
      out.write("			$(\"#studentTblBody\").empty();\r\n");
      out.write("			$.map(students, function(student) {\r\n");
      out.write("				\r\n");
      out.write("				var rowData = \"<tr>\";\r\n");
      out.write("				rowData += \"<td>\" + student.student_id + \"</td>\";\r\n");
      out.write("				rowData += \"<td>\" + student.student_name + \"</td>\";\r\n");
      out.write("				rowData += \"<td>\" + student.dob + \"</td>\";\r\n");
      out.write("				rowData += \"<td>\" + student.gender + \"</td>\";\r\n");
      out.write("				rowData += \"<td>\" + student.contact + \"</td>\";\r\n");
      out.write("				rowData += \"<td>\" + student.class_name + \"</td>\";\r\n");
      out.write("				rowData += \"<td>\" + student.course_name + \"</td>\";\r\n");
      out.write("\r\n");
      out.write("				rowData += \"<td>\";\r\n");
      out.write("				rowData += \"<button class='btn btn-sm btn-primary' onclick='editStudent(\" + student.student_id + \")'>Edit</button> \";\r\n");
      out.write("				rowData += \"<button type='button' class='btn btn-sm btn-danger' onclick='doDelete(\" + student.student_id + \", event)'>Delete</button>\";\r\n");
      out.write("				rowData += \"</td>\";\r\n");
      out.write("\r\n");
      out.write("				rowData += \"</tr>\";\r\n");
      out.write("\r\n");
      out.write("				console.log(rowData);\r\n");
      out.write("				$(\"#studentTblBody\").append(rowData);\r\n");
      out.write("			});			\r\n");
      out.write("		},\r\n");
      out.write("		error: function(){\r\n");
      out.write("			alert('Error fetching student data');\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function validateInfo(){\r\n");
      out.write("	\r\n");
      out.write("	// JQuery Valisation\r\n");
      out.write("	\r\n");
      out.write("	$(\"#nameError\").html('');\r\n");
      out.write("	$('#dobError').html('');\r\n");
      out.write("	$('#genderError').html('');\r\n");
      out.write("	$('#contactError').html('');\r\n");
      out.write("	$('#classError').html('');\r\n");
      out.write("	$('#courseError').html('');\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	var name = $('input[name=\"name\"]').val().trim();\r\n");
      out.write("	console.log('Name: '+name);\r\n");
      out.write("	\r\n");
      out.write("	var dob = $(\"#dob\").val().trim();\r\n");
      out.write("	console.log('Dob: '+dob);\r\n");
      out.write("	\r\n");
      out.write("	var gender = $('input[name=\"gender\"]:checked').val();\r\n");
      out.write("	console.log('Gender: '+gender);\r\n");
      out.write("	\r\n");
      out.write("	var contact = $(\"#contact\").val().trim();\r\n");
      out.write("	console.log('Console: '+contact);\r\n");
      out.write("	\r\n");
      out.write("	var classes = $(\"#class_id\").val().trim();\r\n");
      out.write("	console.log('Class: '+classes);\r\n");
      out.write("	\r\n");
      out.write("	var courses = $(\"#course_id\").val().trim();\r\n");
      out.write("	console.log('Course:+ '+courses);\r\n");
      out.write("	\r\n");
      out.write("	var student_id = $(\"#student_id\").val().trim();\r\n");
      out.write("	\r\n");
      out.write("	var isValid = true;\r\n");
      out.write("	\r\n");
      out.write("	if(name === ''){\r\n");
      out.write("		$(\"#nameError\").html(\"Name is required.\");\r\n");
      out.write("		isValid = false;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(dob === ''){\r\n");
      out.write("		$(\"#dobError\").html(\"Pick a date.\");\r\n");
      out.write("		isValid = false;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(gender === ''){\r\n");
      out.write("		$(\"#genderError\").html(\"Select a gender.\");\r\n");
      out.write("		isValid = false;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(contact === '' || contact.length !== 10 || isNaN(contact)){\r\n");
      out.write("		$(\"#contactError\").html(\"Please enter a valid 10-digit contact.\");\r\n");
      out.write("		isValid = false;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(classes === ''){\r\n");
      out.write("		$(\"#classError\").html(\"Please select class.\");\r\n");
      out.write("		isValid = false;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(courses === ''){\r\n");
      out.write("		$(\"#courseError\").html(\"Please select course.\");\r\n");
      out.write("		isValid = false;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	 \r\n");
      out.write("	if(isValid){\r\n");
      out.write("        //document.studentForm.submit();\r\n");
      out.write("        $.ajax({\r\n");
      out.write("        	url : 'students',\r\n");
      out.write("        	type : 'POST',\r\n");
      out.write("        	data:  $(\"#contactForm\").serialize(),\r\n");
      out.write("        	success: function(data){\r\n");
      out.write("        		console.log(data);\r\n");
      out.write("				if(data === 'success'){\r\n");
      out.write("					window.location.href = \"Students.jsp\";\r\n");
      out.write("				}else{\r\n");
      out.write("					console.log(\"Not saved....\");\r\n");
      out.write("				}\r\n");
      out.write("        		\r\n");
      out.write("        	},failure: function(data){\r\n");
      out.write("        		alert('Something wrong. Please try again');\r\n");
      out.write("        	}\r\n");
      out.write("        	\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function doDelete(student_id){\r\n");
      out.write("	if (confirm(\"Delete this student?\")){\r\n");
      out.write("		$(\"#actionID\").val('delete');\r\n");
      out.write("		$('#student_id').val(student_id);\r\n");
      out.write("		$.ajax({\r\n");
      out.write("        	url : 'students',\r\n");
      out.write("        	type : 'POST',\r\n");
      out.write("        	data:  $(\"#contactForm\").serialize(),\r\n");
      out.write("        	success: function(data){\r\n");
      out.write("        		console.log(data);\r\n");
      out.write("				if(data === 'success'){\r\n");
      out.write("					window.location.href = \"Students.jsp\";\r\n");
      out.write("				}else{\r\n");
      out.write("					console.log(\"Not saved....\");\r\n");
      out.write("				}\r\n");
      out.write("        		\r\n");
      out.write("        	},failure: function(data){\r\n");
      out.write("        		alert('Something wrong. Please try again');\r\n");
      out.write("        	}\r\n");
      out.write("        	\r\n");
      out.write("        });\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function doCheckContact(contact){\r\n");
      out.write("	$('#contactError').html('');\r\n");
      out.write("	console.log(\"Contact: \"+contact);\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: \"studentContact\",\r\n");
      out.write("		type: \"GET\",\r\n");
      out.write("		data:{\r\n");
      out.write("			ContactVal : contact\r\n");
      out.write("		},\r\n");
      out.write("		success:function(resp){\r\n");
      out.write("			console.log(resp);\r\n");
      out.write("			if(resp === 'exist'){\r\n");
      out.write("				$('#contactError').html(\"This contact is already used. Please enter another.\");\r\n");
      out.write("			}\r\n");
      out.write("		},\r\n");
      out.write("		failure:function(data){\r\n");
      out.write("			alert('Invalid request');\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function loadClassesList(){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: 'class',\r\n");
      out.write("		type: 'GET',\r\n");
      out.write("		data : {action: 'list'},\r\n");
      out.write("		success : function(data){\r\n");
      out.write("			var res = eval(data);\r\n");
      out.write("			console.log(res);\r\n");
      out.write("			\r\n");
      out.write("			$.map(res, function(cls){\r\n");
      out.write("				console.log(cls.classId + ' '+ cls.className);\r\n");
      out.write("				var optionData = '<option value=' + cls.classId + '>' + cls.className + '</option>';\r\n");
      out.write("				$('#class_id').append(optionData),\r\n");
      out.write("				$('#searchClassId').append(optionData)\r\n");
      out.write("			});\r\n");
      out.write("		},\r\n");
      out.write("		failure: function(data){\r\n");
      out.write("			console.log(data);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function loadCoursesList(){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: 'course',\r\n");
      out.write("		type: 'GET',\r\n");
      out.write("		data : {action: 'list'},\r\n");
      out.write("		success : function(data){\r\n");
      out.write("			var res = eval(data);\r\n");
      out.write("			console.log(res);\r\n");
      out.write("			\r\n");
      out.write("			$.map(res, function(course){\r\n");
      out.write("				console.log(course.course_id + ' '+ course.course_name);\r\n");
      out.write("				var optionData = '<option value=' + course.course_id + '>' + course.course_name + '</option>';\r\n");
      out.write("				$('#course_id').append(optionData),\r\n");
      out.write("				$('#searchCourseId').append(optionData)\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("		},\r\n");
      out.write("		failure: function(data){\r\n");
      out.write("			console.log(data);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function editStudent(studentId){\r\n");
      out.write("	$('#addStudentModalLabel').text('Edit Student');\r\n");
      out.write("	$('#submitButton').text('Update Student');\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: 'students',\r\n");
      out.write("		type: 'GET',\r\n");
      out.write("		data: { student_id: studentId },\r\n");
      out.write("		success: function(data){\r\n");
      out.write("			console.log(data);\r\n");
      out.write("			var student = eval(data);\r\n");
      out.write("			if(student){\r\n");
      out.write("				$(\"#actionID\").val('update');\r\n");
      out.write("				$('#student_id').val(student.student_id);\r\n");
      out.write("				$('#student_name').val(student.student_name);\r\n");
      out.write("				\r\n");
      out.write("				var today = new Date(student.dob);\r\n");
      out.write("			    var dd = String(today.getDate()).padStart(2, '0');\r\n");
      out.write("			    var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!\r\n");
      out.write("			    var yyyy = today.getFullYear();\r\n");
      out.write("\r\n");
      out.write("			    var formattedDate = yyyy + '-' + mm + '-' + dd;\r\n");
      out.write("\r\n");
      out.write("				$('#dob').val(formattedDate);\r\n");
      out.write("				\r\n");
      out.write("                $('input[name=\"gender\"][value=\"' + student.gender + '\"]').prop('checked', true);\r\n");
      out.write("                $('#contact').val(student.contact);\r\n");
      out.write("                $('#class_id').val(student.class_id);\r\n");
      out.write("                $('#course_id').val(student.course_id);\r\n");
      out.write("                $('#addbtnID').text('Update');\r\n");
      out.write("                $('#addStudentModal').modal('show');\r\n");
      out.write("			}else{\r\n");
      out.write("				alert('Failed to load student data.');\r\n");
      out.write("			}			\r\n");
      out.write("		},\r\n");
      out.write("		error: function(){\r\n");
      out.write("			alert('Error fetching student data.');\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(document).on('click', '[data-bs-target=\"#addStudentModal\"]', function(){\r\n");
      out.write("	\r\n");
      out.write("	$('#addStudentModalLabel').text(\"Add New Student\");\r\n");
      out.write("	$('#submitButton').text('Add Student');\r\n");
      out.write("	$('#contactForm')[0].reset();\r\n");
      out.write("	$('#student_id').val('');\r\n");
      out.write("	$('#nameError, #dobError, #genderError, #contactError, #classError, #courseError').html('');\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function loadpage(pageno) {\r\n");
      out.write("    document.studentform.cpage.value = pageno;\r\n");
      out.write("    document.studentform.submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
