/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-09-01 05:53:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import School.trn.trn_teachers.TeachersDTO;
import School.Mst.Mst_departments.DepartmentsDTO;
import School.Mst.Mst_designation.DesignationDTO;

public final class Teachers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/session_expired.jsp", Long.valueOf(1755837901527L));
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1756016672277L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("School.trn.trn_teachers.TeachersDTO");
    _jspx_imports_classes.add("School.Mst.Mst_departments.DepartmentsDTO");
    _jspx_imports_classes.add("School.Mst.Mst_designation.DesignationDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Teachers List</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("    body {\r\n");
      out.write("        background-image: url('Images/imgg.jpg');\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        background-repeat: no-repeat;\r\n");
      out.write("        background-attachment: fixed;\r\n");
      out.write("        background-position: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container {\r\n");
      out.write("        background-color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    .table-transparent {\r\n");
      out.write("  color: #fff !important;   /* make all text white */\r\n");
      out.write("  background-color: transparent !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-transparent thead, \r\n");
      out.write(".table-transparent tbody, \r\n");
      out.write(".table-transparent th, \r\n");
      out.write(".table-transparent td, \r\n");
      out.write(".table-transparent tr {\r\n");
      out.write("  background-color: transparent !important;\r\n");
      out.write("  color: #fff !important;   /* force white text */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-transparent.table-striped > tbody > tr:nth-of-type(odd) {\r\n");
      out.write("  --bs-table-accent-bg: rgba(255,255,255,0.05) !important; /* faint stripe */\r\n");
      out.write("  color: #fff !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container mt-5 text-light\"\r\n");
      out.write("style=\"background-color: rgba(0,0,0,0.5); border-radius: 12px; padding:20px;\">\r\n");
      out.write('\r');
      out.write('\n');

String logedInUser = session.getAttribute("logedInUser") == null ? "" : (String) session.getAttribute("logedInUser");
if(logedInUser.equals("")){
	response.sendRedirect("HomePage.jsp");
}

      out.write(' ');
      out.write("\r\n");
      out.write("<!-- nav.jsp -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark py-4\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"welcome.jsp\">\r\n");
      out.write("    	<img src=\"Images/School2.png\" alt=\"Logo\" width=\"30\" height=\"30\" class=\"d-inline-block align-text-top me-2\">\r\n");
      out.write("    	<img src=\"Images/logo (1).png\" alt=\"Logo\" width=\"200\" height=\"30\" class=\"d-inline-block align-text-top me-2\">\r\n");
      out.write("  \r\n");
      out.write("    </a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#mainNav\"\r\n");
      out.write("            aria-controls=\"mainNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"mainNav\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle fs-6 text-light\" href=\"#\" id=\"mastersDropdown\" role=\"button\"\r\n");
      out.write("             data-bs-toggle=\"dropdown\" aria-expanded=\"false\" >Masters</a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"mastersDropdown\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"class\">Classes</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"course\">Courses</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"department\">Departments</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"designation\">Designations</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"examTypes\">Exam Types</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"feeTypes\">Fee Types</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"subjects\">Subjects</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"userRoles\">User Roles</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle fs-6 text-light\" href=\"#\" id=\"transactionsDropdown\" role=\"button\"\r\n");
      out.write("             data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Transactions</a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"mastersDropdown\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"marksList\">Marks</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"Teachers.jsp\">Teachers</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"Students.jsp\">Students</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"logout.jsp\">Logout</a>\r\n");
      out.write("        </li>\r\n");
      out.write("		\r\n");
      out.write("      </ul>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Notification bell -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");

    int rows = request.getParameter("rows") == null ? 10 : Integer.parseInt(request.getParameter("rows"));
    String searchQuery = request.getParameter("query") == null ? "" : request.getParameter("query");
    String selectedDeptId = request.getParameter("dept_id");
    String selectedDesigId = request.getParameter("desig_id");
    String sortColumn = (String) request.getAttribute("sortColumn");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<h2 class=\"mb-4\">Teachers List</h2>\r\n");
      out.write("\r\n");
      out.write("<form action=\"teachersList\" method=\"get\" name=\"searchform\" class=\"row gx-3 gy-2 align-items-center mb-4\">\r\n");
      out.write("    <input type=\"hidden\" name=\"cpage\" value=\"1\"/>\r\n");
      out.write("\r\n");
      out.write("    <!-- Search Box -->\r\n");
      out.write("    <div class=\"col-auto\"> \r\n");
      out.write("        <input type=\"text\" name=\"query\" value=\"");
      out.print( searchQuery );
      out.write("\" class=\"form-control\" placeholder=\"Enter search term\" id=\"query\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Department Dropdown -->\r\n");
      out.write("    <div class=\"col-auto\">\r\n");
      out.write("        <select class=\"form-select\" name=\"dept_id\" id=\"searchDeptId\">\r\n");
      out.write("            <option value=\"\">-- Select Department --</option>\r\n");
      out.write("            \r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Designation Dropdown -->\r\n");
      out.write("    <div class=\"col-auto\">\r\n");
      out.write("        <select class=\"form-select\" name=\"desig_id\" id=\"searchDesigId\">\r\n");
      out.write("            <option value=\"\">-- Select Designation --</option>\r\n");
      out.write("            \r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Rows Per Page -->\r\n");
      out.write("    <div class=\"col-auto\">\r\n");
      out.write("        <input type=\"number\" id=\"rows\" value=\"");
      out.print( rows );
      out.write("\" name=\"rows\" class=\"form-control\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Sort Dropdown -->\r\n");
      out.write("    <div class=\"col-auto\">\r\n");
      out.write("        <select class=\"form-select\" name=\"sort_column\">\r\n");
      out.write("            <option value=\"teacher_id\" ");
      out.print( "teacher_id".equals(sortColumn) ? "selected" : "" );
      out.write(">Sort by ID</option>\r\n");
      out.write("            <option value=\"teacher_name\" ");
      out.print( "teacher_name".equals(sortColumn) ? "selected" : "" );
      out.write(">Sort by Name</option>\r\n");
      out.write("            <option value=\"contact\" ");
      out.print( "contact".equals(sortColumn) ? "selected" : "" );
      out.write(">Sort by Contact</option>\r\n");
      out.write("            <option value=\"dept_name\" ");
      out.print( "dept_name".equals(sortColumn) ? "selected" : "" );
      out.write(">Sort by Department</option>\r\n");
      out.write("            <option value=\"designation_name\" ");
      out.print( "designation_name".equals(sortColumn) ? "selected" : "" );
      out.write(">Sort by Designation</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Submit -->\r\n");
      out.write("    <div class=\"col-auto\">\r\n");
      out.write("        <button type=button class=\"btn btn-primary\" onclick=\"loadTeacherList()\">Search</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<table class=\"table table-bordered table-hover table-transparent table-striped\">\r\n");
      out.write("    <thead>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <th>ID</th>\r\n");
      out.write("        <th>Name</th>\r\n");
      out.write("        <th>Email</th>\r\n");
      out.write("        <th>Contact</th>\r\n");
      out.write("        <th>Department</th>\r\n");
      out.write("        <th>Designation</th>\r\n");
      out.write("        <th>Actions</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    <tbody id=\"teacherTblBody\">\r\n");
      out.write("    \r\n");
      out.write("    </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<div> <ul id=\"paginationID\" class=\"d-flex\" style=\"list-style: none;\"></ul> </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"mt-4\">\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-warning\" data-bs-toggle=\"modal\" data-bs-target=\"#addTeacherModal\">\r\n");
      out.write("  Add New Teacher\r\n");
      out.write("</button>\r\n");
      out.write("<!-- Add Teacher Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"addTeacherModal\" tabindex=\"-1\" aria-labelledby=\"addTeacherModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("    <div class=\"modal-content text-dark\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"addTeacherModalLabel\">Add New Teacher</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <form action=\"teachers\" method=\"post\" name=\"teacherform\" id=\"contactForm\">\r\n");
      out.write("        	<input type=\"hidden\" name=\"teacher_id\" id=\"teacher_id\">\r\n");
      out.write("        \r\n");
      out.write("        	<input type =\"hidden\" name=\"action\" id=\"actionID\">\r\n");
      out.write("          <div class=\"row mb-3\">\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("              <input type=\"text\" name=\"name\" id=\"teacher_name\" class=\"form-control\" placeholder=\"Teacher Name\" required>\r\n");
      out.write("              <span id=\"nameError\" style=\"color: red\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("              <input type=\"text\" name=\"email\" id=\"emailid\" class=\"form-control\" placeholder=\"Teacher Email\" onblur=\"doCheckEmail(this.value)\" required>\r\n");
      out.write("              <span id=\"emailError\" style=\"color: red\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("              <input type=\"text\" name=\"contact\" id=\"contactid\" class=\"form-control\" placeholder=\"Contact Number\" onblur=\"doCheckContact(this.value)\" required maxlength=\"10\">\r\n");
      out.write("              <span id=\"contactError\" style=\"color: red\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"row mb-3\">\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("              <select name=\"dept_id\" id=\"dept_id\" class=\"form-select\" required>\r\n");
      out.write("                <option value=\"\">Select Department</option>\r\n");
      out.write("              </select>\r\n");
      out.write("              <span id=\"deptError\" style=\"color: red\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("              <select name=\"designation_id\" id=\"designation_id\" class=\"form-select\" required>\r\n");
      out.write("                <option value=\"\">Select Designation</option>\r\n");
      out.write("              </select>\r\n");
      out.write("              <span id=\"desigError\" style=\"color: red\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"d-grid gap-2\">\r\n");
      out.write("            <button type=\"button\" onclick=\"validateInfo()\" class=\"btn btn-primary\" id=\"addbtnID\">Add Teacher</button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\" integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("	 console.log('page load');\r\n");
      out.write("	 loadTeacherList();\r\n");
      out.write("	 loadDepartmentList();\r\n");
      out.write("	 loadDesignationList();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function loadTeacherList(){\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: 'teachersList',\r\n");
      out.write("		type: 'GET',\r\n");
      out.write("		data: {\r\n");
      out.write("			\r\n");
      out.write("			query : $(\"#query\").val(),\r\n");
      out.write("			rows : $(\"#rows\").val(),\r\n");
      out.write("			searchQuery : $(\"#query\").val(),\r\n");
      out.write("			selectedDeptId : $(\"#searchDeptId\").val(),\r\n");
      out.write("			selectedDesigId : $(\"#selectedDesigId\").val(),\r\n");
      out.write("			sortColumn : $(\"select[name='sort_column']\").val(),\r\n");
      out.write("            cpage: 1\r\n");
      out.write("		},\r\n");
      out.write("		success: function(data){\r\n");
      out.write("			\r\n");
      out.write("			var res = eval(data);\r\n");
      out.write("			console.log(res);\r\n");
      out.write("			\r\n");
      out.write("			var teachers = res.teachers;\r\n");
      out.write("			console.log(teachers);\r\n");
      out.write("			$(\"#teacherTblBody\").empty();\r\n");
      out.write("			$.map( teachers, function( teacher ) {\r\n");
      out.write("				var rowData = createRowElement(teacher);\r\n");
      out.write("\r\n");
      out.write("				$(\"#teacherTblBody\").append(rowData);\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("		},\r\n");
      out.write("		error: function(){\r\n");
      out.write("			alert('Error fetching teacher data');\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function createRowElement(teacher){\r\n");
      out.write("	var  rowData = \"<tr>\";\r\n");
      out.write("	rowData +=\"<td>\"+ teacher.teacher_id +\"</td>\";\r\n");
      out.write("	rowData +=\"<td>\"+ teacher.name +\"</td>\";\r\n");
      out.write("	rowData +=\"<td>\"+ teacher.email +\"</td>\";\r\n");
      out.write("	rowData +=\"<td>\"+ teacher.contact +\"</td>\";\r\n");
      out.write("	rowData +=\"<td>\"+ teacher.dept_name +\"</td>\";\r\n");
      out.write("	rowData +=\"<td>\"+ teacher.designation_name +\"</td>\";\r\n");
      out.write("	rowData += \"<td>\";\r\n");
      out.write("	rowData += \"<button class='btn btn-sm btn-primary' onclick='editTeacher(\" + teacher.teacher_id + \")'>Edit</button> \";\r\n");
      out.write("	rowData += \"<button type='button' class='btn btn-sm btn-danger' onclick='doDelete(\" + teacher.teacher_id + \", event)'>Delete</button>\";\r\n");
      out.write("	rowData += \"</td>\";\r\n");
      out.write("	rowData +=\"</tr>\";\r\n");
      out.write("	return rowData;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(\"#emailid\").val();\r\n");
      out.write("function validateInfo(){\r\n");
      out.write("    // Clear previous errors\r\n");
      out.write("    $(\"#nameError\").html('');\r\n");
      out.write("    $(\"#emailError\").html('');\r\n");
      out.write("    $(\"#contactError\").html('');\r\n");
      out.write("    $(\"#deptError\").html('');\r\n");
      out.write("    $(\"#desigError\").html('');\r\n");
      out.write("//     document.getElementById(\"nameError\").innerHTML = '';\r\n");
      out.write("//     document.getElementById(\"emailError\").innerHTML = '';\r\n");
      out.write("//     document.getElementById(\"contactError\").innerHTML = '';\r\n");
      out.write("//     document.getElementById(\"deptError\").innerHTML = '';\r\n");
      out.write("//     document.getElementById(\"desigError\").innerHTML = '';\r\n");
      out.write("\r\n");
      out.write("    var name = $('input[name=\"name\"]').val().trim();\r\n");
      out.write("    console.log('Name: ' + name);\r\n");
      out.write("    \r\n");
      out.write("    var email = $(\"#emailid\").val().trim();\r\n");
      out.write("    console.log(\"Email: \"+email);\r\n");
      out.write("    \r\n");
      out.write("    var contact = $('#contactid').val().trim();\r\n");
      out.write("	console.log(\"Contact: \"+contact);\r\n");
      out.write("    \r\n");
      out.write("    var dept = $('#dept_id').val().trim();\r\n");
      out.write("    console.log(\"Department: \"+dept);\r\n");
      out.write("    \r\n");
      out.write("    var desig = $('#designation_id').val().trim();\r\n");
      out.write("    console.log(\"Designation: \"+desig);\r\n");
      out.write("    \r\n");
      out.write("    var emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\r\n");
      out.write("    var isValid = true;\r\n");
      out.write("    \r\n");
      out.write("    if (name === '') {\r\n");
      out.write("        $(\"#nameError\").html(\"Name is required.\");\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (email === '' || !emailRegex.test(email)) {\r\n");
      out.write("        $(\"#emailError\").html(\"Enter valid email.\");\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if (contact === '' || contact.length !== 10 || isNaN(contact)){\r\n");
      out.write("    	$(\"#contactError\").html(\"Please enter a valid 10-digit contact.\");\r\n");
      out.write("    	isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if (dept === ''){\r\n");
      out.write("    	$(\"#deptError\").html(\"Select a department.\")\r\n");
      out.write("    	isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if(desig === ''){\r\n");
      out.write("    	$(\"#desigError\").html(\"Select a designation.\")\r\n");
      out.write("    	isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("    if(isValid){\r\n");
      out.write("       // document.teacherform.submit();\r\n");
      out.write("       \r\n");
      out.write("       $.ajax({\r\n");
      out.write("    	   url : 'teachers',\r\n");
      out.write("    	   type : 'POST',\r\n");
      out.write("    	   data : $('#contactForm').serialize(),\r\n");
      out.write("    	   success : function(data){\r\n");
      out.write("    		   console.log(data);\r\n");
      out.write("    		   if(data === 'success'){\r\n");
      out.write("    			   \r\n");
      out.write("    			   loadTeacherList();\r\n");
      out.write("    			   $('#addTeacherModal').modal('hide');\r\n");
      out.write("    		   }else{\r\n");
      out.write("    			   console.log(\"Not saved....\");\r\n");
      out.write("    		   }\r\n");
      out.write("    	   },failure: function(data){\r\n");
      out.write("    		   alert('Something wrong. Please try again');\r\n");
      out.write("    	   }\r\n");
      out.write("       });\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function doDelete(teacher_id){\r\n");
      out.write("	\r\n");
      out.write("	if(confirm(\"Delete this teacher?\")){\r\n");
      out.write("		$(\"#actionID\").val('delete');\r\n");
      out.write("		$('#teacher_id').val(teacher_id);\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : 'teachers',\r\n");
      out.write("		 	   type : 'POST',\r\n");
      out.write("		 	   data : $('#contactForm').serialize(),\r\n");
      out.write("		 	   success : function(data){\r\n");
      out.write("		 		   console.log(data);\r\n");
      out.write("		 		   if(data === 'success'){\r\n");
      out.write("		 			   \r\n");
      out.write("		 			  loadTeacherList();\r\n");
      out.write("		 			 $('#addTeacherModal').modal('hide');\r\n");
      out.write("		 		   }else{\r\n");
      out.write("		 			   console.log(\"Not saved....\");\r\n");
      out.write("		 		   }\r\n");
      out.write("		 	   },failure: function(data){\r\n");
      out.write("		 		   alert('Something wrong. Please try again');\r\n");
      out.write("		 	   }\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function doCheckEmail(email){\r\n");
      out.write("	 $(\"#emailError\").html('');\r\n");
      out.write("	console.log(\"Email: \" + email);\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: \"teacherinfo\",\r\n");
      out.write("		type: 'GET',\r\n");
      out.write("		data: {\r\n");
      out.write("			emailVal: email\r\n");
      out.write("		},\r\n");
      out.write("		success:function(resp){\r\n");
      out.write("			console.log(resp);\r\n");
      out.write("			if(resp === 'exist'){\r\n");
      out.write("				$(\"#emailError\").html(\"This email is already used. Please enter another.\");\r\n");
      out.write("			}\r\n");
      out.write("		},\r\n");
      out.write("		failure:function(data){\r\n");
      out.write("			alert('Invalid request');\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function doCheckContact(contact){\r\n");
      out.write("	$('#contactError').html('');\r\n");
      out.write("	console.log(\"Contact: \"+contact);\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: \"teacherContact\",\r\n");
      out.write("		type: 'GET',\r\n");
      out.write("		data:{\r\n");
      out.write("			contactVal : contact\r\n");
      out.write("		},\r\n");
      out.write("		success:function(resp){\r\n");
      out.write("			console.log(resp);\r\n");
      out.write("			if(resp === 'exist'){\r\n");
      out.write("				$(\"#contactError\").html(\"This contact is already used. Please enter another.\");\r\n");
      out.write("			}\r\n");
      out.write("		},\r\n");
      out.write("		failure:function(data){\r\n");
      out.write("			alert('Invalid request');\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function loadDepartmentList(){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: 'department',\r\n");
      out.write("		type: 'GET',\r\n");
      out.write("		data: {action: 'list'},\r\n");
      out.write("		success: function(data){\r\n");
      out.write("			var res = eval(data);\r\n");
      out.write("			console.log(res);\r\n");
      out.write("			\r\n");
      out.write("			$.map( res, function( dept ) {\r\n");
      out.write("				console.log(dept.dept_id  + ' ' + dept.dept_name);\r\n");
      out.write("				var optionData = '<option value='+ dept.dept_id+'>'+ dept.dept_name +'</option>';\r\n");
      out.write("				$(\"#dept_id\").append(optionData);\r\n");
      out.write("				$(\"#searchDeptId\").append(optionData);\r\n");
      out.write("			});\r\n");
      out.write("		},\r\n");
      out.write("		failure: function(data){\r\n");
      out.write("			console.log(data);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function loadDesignationList(){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:'designation',\r\n");
      out.write("		type: 'GET',\r\n");
      out.write("		data: {action: 'list'},\r\n");
      out.write("		success: function(data){\r\n");
      out.write("			var res = eval(data);\r\n");
      out.write("			console.log(res);\r\n");
      out.write("			\r\n");
      out.write("			$.map(res, function(desig){\r\n");
      out.write("				console.log(desig.designation_id + ' ' + desig.designation_name);\r\n");
      out.write("				var optionData = '<option value='+ desig.designation_id +'>' + desig.designation_name + '</option>';\r\n");
      out.write("				$(\"#designation_id\").append(optionData);\r\n");
      out.write("				$(\"#searchDesigId\").append(optionData)\r\n");
      out.write("			});\r\n");
      out.write("		},\r\n");
      out.write("		failure: function(data){\r\n");
      out.write("			console.log(data);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function editTeacher(teacherId){\r\n");
      out.write("	$('#addTeacherModalLabel').text('Edit Teacher');\r\n");
      out.write("	$('#submitButton').text('Update Teacher');\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: 'teachers',\r\n");
      out.write("		type: 'GET',\r\n");
      out.write("		data: { teacher_id : teacherId},\r\n");
      out.write("		success: function(data){\r\n");
      out.write("			console.log(data);\r\n");
      out.write("			var teacher = eval(data);\r\n");
      out.write("			if(teacher){\r\n");
      out.write("				$(\"#actionID\").val('update');\r\n");
      out.write("				$('#teacher_id').val(teacher.teacher_id);\r\n");
      out.write("				$('#teacher_name').val(teacher.name);\r\n");
      out.write("				$('#emailid').val(teacher.email);\r\n");
      out.write("				$('#contactid').val(teacher.contact);\r\n");
      out.write("				$('#dept_id').val(teacher.dept_id);\r\n");
      out.write("				$('#designation_id').val(teacher.designation_id);\r\n");
      out.write("				$('#addbtnID').text('Update');\r\n");
      out.write("				$('#addTeacherModal').modal('show');\r\n");
      out.write("			}else{\r\n");
      out.write("				alert('Failed to load teacher data.')\r\n");
      out.write("			}\r\n");
      out.write("		},\r\n");
      out.write("		error: function(){\r\n");
      out.write("			alert('Error fetching teacher data');\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(document).on('click','[data-bs-target=\"#addTeacherModal\"]', function(){\r\n");
      out.write("	$('#addTeacherModalLabel').text(\"Add New Teacher\");\r\n");
      out.write("	$('#submitButton').text('Add Teacher');\r\n");
      out.write("	$('#contactForm')[0].reset();\r\n");
      out.write("	$('#teacher_id').val('');\r\n");
      out.write("	$('#nameError, #emailError, #contactError, #deptError, #desigError').html('');\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function loadpage(pageno) {\r\n");
      out.write("    document.searchform.cpage.value = pageno;\r\n");
      out.write("    document.searchform.submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
