/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-27 13:52:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import School.trn.trn_teachers.TeachersDTO;
import School.Mst.Mst_departments.DepartmentsDTO;
import School.Mst.Mst_designation.DesignationDTO;

public final class TeachersUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("School.trn.trn_teachers.TeachersDTO");
    _jspx_imports_classes.add("School.Mst.Mst_departments.DepartmentsDTO");
    _jspx_imports_classes.add("School.Mst.Mst_designation.DesignationDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Update Teacher</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("    body {\r\n");
      out.write("        background-image: url('Images/img5.jpg');\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        background-repeat: no-repeat;\r\n");
      out.write("        background-attachment: fixed;\r\n");
      out.write("        background-position: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container {\r\n");
      out.write("        background-color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container mt-5 bg-dark\">\r\n");
      out.write("    <h2 class=\"mb-4\">Update Teacher</h2>\r\n");
      out.write("\r\n");
      out.write("    ");

        TeachersDTO teacher = (TeachersDTO) request.getAttribute("teacher");
        List<DepartmentsDTO> departments = (List<DepartmentsDTO>) request.getAttribute("departments");
        List<DesignationDTO> designations = (List<DesignationDTO>) request.getAttribute("designations");

        if (teacher != null) {
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <form action=\"updateTeacher\" method=\"post\" name=\"updateForm\" onsubmit=\"return validateUpdate();\">\r\n");
      out.write("        <!-- Hidden field to keep teacher ID -->\r\n");
      out.write("        <input type=\"hidden\" name=\"teacher_id\" value=\"");
      out.print( teacher.getTeacher_id() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row mb-3\">\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("                <input type=\"text\" name=\"name\" class=\"form-control\" placeholder=\"Teacher Name\"\r\n");
      out.write("                       value=\"");
      out.print( teacher.getName() );
      out.write("\" required>\r\n");
      out.write("                <span id=\"nameError\" style=\"color: red\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("                <input type=\"text\" name=\"email\" id=\"emailid\" class=\"form-control\" placeholder=\"Teacher Email\"\r\n");
      out.write("                       value=\"");
      out.print( teacher.getEmail() );
      out.write("\" required>\r\n");
      out.write("                <span id=\"emailError\" style=\"color: red\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("                <input type=\"text\" name=\"contact\" id=\"contactid\" class=\"form-control\" placeholder=\"Contact Number\"\r\n");
      out.write("                       value=\"");
      out.print( teacher.getContact() );
      out.write("\" required maxlength=\"10\">\r\n");
      out.write("                <span id=\"contactError\" style=\"color: red\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row mb-3\">\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("                <select name=\"dept_id\" id=\"dept_id\" class=\"form-select\" required>\r\n");
      out.write("                    <option value=\"\">Select Department</option>\r\n");
      out.write("                    ");

                        if (departments != null) {
                            for (DepartmentsDTO dept : departments) {
                                String selected = (dept.getDept_id() == teacher.getDept_id()) ? "selected" : "";
                    
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print( dept.getDept_id() );
      out.write('"');
      out.write(' ');
      out.print( selected );
      out.write('>');
      out.print( dept.getDept_name() );
      out.write("</option>\r\n");
      out.write("                    ");

                            }
                        }
                    
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("                <span id=\"deptError\" style=\"color: red\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("                <select name=\"designation_id\" id=\"designation_id\" class=\"form-select\" required>\r\n");
      out.write("                    <option value=\"\">Select Designation</option>\r\n");
      out.write("                    ");

                        if (designations != null) {
                            for (DesignationDTO desig : designations) {
                                String selected = (desig.getDesignation_id() == teacher.getDesignation_id()) ? "selected" : "";
                    
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print( desig.getDesignation_id() );
      out.write('"');
      out.write(' ');
      out.print( selected );
      out.write('>');
      out.print( desig.getDesignation_name() );
      out.write("</option>\r\n");
      out.write("                    ");

                            }
                        }
                    
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("                <span id=\"desigError\" style=\"color: red\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"d-grid gap-2\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-success\">Update Teacher</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"mt-3\">\r\n");
      out.write("        <a href=\"teachersList\" class=\"btn btn-secondary\">Back to List</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");

        } else {
    
      out.write("\r\n");
      out.write("        <div class=\"alert alert-danger\">Teacher data not found!</div>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\" integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function validateUpdate() {\r\n");
      out.write("	\r\n");
      out.write("	// Clear previous errors\r\n");
      out.write("    $(\"#nameError\").html('');\r\n");
      out.write("    $(\"#emailError\").html('');\r\n");
      out.write("    $(\"#contactError\").html('');\r\n");
      out.write("    $(\"#deptError\").html('');\r\n");
      out.write("    $(\"#desigError\").html('');\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("   /*  document.getElementById(\"nameError\").innerHTML = '';\r\n");
      out.write("    document.getElementById(\"emailError\").innerHTML = '';\r\n");
      out.write("    document.getElementById(\"contactError\").innerHTML = '';\r\n");
      out.write("    document.getElementById(\"deptError\").innerHTML = '';\r\n");
      out.write("    document.getElementById(\"desigError\").innerHTML = ''; */\r\n");
      out.write("\r\n");
      out.write("    var name = $('input[name=\"name\"]').val().trim();\r\n");
      out.write("    console.log('Name: ' + name);\r\n");
      out.write("\r\n");
      out.write("    var email = $(\"#emailid\").val().trim();\r\n");
      out.write("    console.log('Email: '+email)\r\n");
      out.write("    \r\n");
      out.write("    var contact = $(\"#contactid\").val().trim();\r\n");
      out.write("    console.log('Contact: '+contact)\r\n");
      out.write("    \r\n");
      out.write("    /* \r\n");
      out.write("    var contact = document.getElementById(\"contactid\").value.trim();\r\n");
      out.write("    var dept = document.updateForm.dept_id.value;\r\n");
      out.write("     */\r\n");
      out.write("    \r\n");
      out.write("    var dept = $(\"#dept_id\").val().trim();\r\n");
      out.write("    console.log('Department: '+dept)\r\n");
      out.write("    \r\n");
      out.write("    var desig = $(\"#designation_id\").val().trim(); \r\n");
      out.write("    console.log('Designation: '+desig)\r\n");
      out.write("\r\n");
      out.write("    var emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\r\n");
      out.write("    var isValid = true;\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    if (name === '') {\r\n");
      out.write("        $(\"#nameError\").html(\"Name is required.\");\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (email === '' || !emailRegex.test(email)) {\r\n");
      out.write("        $(\"#emailError\").html(\"Enter valid email.\");\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if (contact === '' || contact.length !== 10 || isNaN(contact)){\r\n");
      out.write("    	$(\"#contactError\").html(\"Please enter a valid 10-digit contact.\");\r\n");
      out.write("    	isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if (dept === ''){\r\n");
      out.write("    	$(\"#deptError\").html(\"Select a department.\")\r\n");
      out.write("    	isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if(desig === ''){\r\n");
      out.write("    	$(\"#desigError\").html(\"Select a designation.\")\r\n");
      out.write("    	isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("    /* \r\n");
      out.write("    if(name === '') {\r\n");
      out.write("        document.getElementById(\"nameError\").innerHTML = \"Name is required.\";\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if(email === '' || !emailRegex.test(email)) {\r\n");
      out.write("        document.getElementById(\"emailError\").innerHTML = \"Enter valid email.\";\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if(contact === '' || contact.length !== 10 || isNaN(contact)) {\r\n");
      out.write("        document.getElementById(\"contactError\").innerHTML = \"Enter 10-digit valid contact.\";\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if(dept === '') {\r\n");
      out.write("        document.getElementById(\"deptError\").innerHTML = \"Select a department.\";\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if(desig === '') {\r\n");
      out.write("        document.getElementById(\"desigError\").innerHTML = \"Select a designation.\";\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write(" */\r\n");
      out.write(" \r\n");
      out.write("    return isValid;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
