/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-09-01 05:52:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" data-bs-theme=\"dark\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>School Management System</title>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css\">\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("      background-color: #121212;\r\n");
      out.write("    }\r\n");
      out.write("    .sidebar {\r\n");
      out.write("      min-height: 100vh;\r\n");
      out.write("      background-color: #1e1e1e;\r\n");
      out.write("      box-shadow: 2px 0 5px rgba(0,0,0,0.05);\r\n");
      out.write("    }\r\n");
      out.write("    .sidebar .nav-link {\r\n");
      out.write("      color: #ced4da;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("    }\r\n");
      out.write("    .sidebar .nav-link.active {\r\n");
      out.write("      background-color: #343a40;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("    }\r\n");
      out.write("    .card-stat {\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 12px;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      color: #ced4da;\r\n");
      out.write("    }\r\n");
      out.write("    .card-module {\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 12px;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .card-module:hover {\r\n");
      out.write("      transform: translateY(-5px);\r\n");
      out.write("      box-shadow: 0 4px 12px rgba(0,0,0,0.1);\r\n");
      out.write("    }\r\n");
      out.write("    .text-muted {\r\n");
      out.write("      color: #6c757d !important;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <div class=\"col-md-2 sidebar p-3\">\r\n");
      out.write("      <h5 class=\"mb-4\"><i class=\"bi bi-mortarboard\"></i> EduManage</h5>\r\n");
      out.write("      <p class=\"text-muted\">School Management System</p>\r\n");
      out.write("      <hr>\r\n");
      out.write("      <ul class=\"nav flex-column\">\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"#\" class=\"nav-link active\"><i class=\"bi bi-speedometer2 me-2\"></i>Dashboard</a></li>\r\n");
      out.write("        <li class=\"mt-3 text-muted\">Transactions</li>\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"Students.jsp\" class=\"nav-link\"><i class=\"bi bi-people me-2\"></i>Students</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"Teachers.jsp\" class=\"nav-link\"><i class=\"bi bi-person-badge me-2\"></i>Teachers</a></li>\r\n");
      out.write("        <li class=\"mt-3 text-muted\">Masters</li>\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"Courses.jsp\" class=\"nav-link\"><i class=\"bi bi-journal-bookmark me-2\"></i>Courses</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"classes.jsp\" class=\"nav-link\"><i class=\"bi bi-building me-2\"></i>Departments</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"Designations.jsp\" class=\"nav-link\"><i class=\"bi bi-award me-2\"></i>Designations</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"departments.jsp\" class=\"nav-link\"><i class=\"bi bi-house-door me-2\"></i>Classes</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"ExamTypes.jsp\" class=\"nav-link\"><i class=\"bi bi-pen\"></i> Exam Types</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"FeeTypes.jsp\" class=\"nav-link\"><i class=\"bi bi-currency-rupee\"></i> Fee Types</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"Subjects.jsp\" class=\"nav-link\"><i class=\"bi bi-journal-bookmark\"></i> Subjects</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"userRoles.jsp\" class=\"nav-link\"><i class=\"bi bi-people-fill\"></i> User Roles</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <div class=\"col-md-10 p-4\">\r\n");
      out.write("      <h2 class=\"fw-bold\">School Management System</h2>\r\n");
      out.write("      <p class=\"text-muted\">Streamline your educational institution with our comprehensive management platform</p>\r\n");
      out.write("\r\n");
      out.write("      <!-- Stats Row -->\r\n");
      out.write("      <div class=\"row g-3 mb-4\">\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("          <div class=\"card-stat bg-dark\">\r\n");
      out.write("            <h6 >Total Students</h6>\r\n");
      out.write("            <h3 id=\"studentsCount\">0</h3>\r\n");
      out.write("            <span class=\"text-success\">Active enrollment</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("          <div class=\"card-stat bg-dark\">\r\n");
      out.write("            <h6>Faculty Members</h6>\r\n");
      out.write("            <h3 id=\"teachersCount\">0</h3>\r\n");
      out.write("            <span class=\"text-success\">Teaching staff</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("          <div class=\"card-stat bg-dark\">\r\n");
      out.write("            <h6>Active Courses</h6>\r\n");
      out.write("            <h3 id=\"coursesCount\">0</h3>\r\n");
      out.write("            <span class=\"text-success\">Available courses</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("          <div class=\"card-stat bg-dark\">\r\n");
      out.write("            <h6>Departments</h6>\r\n");
      out.write("            <h3 id=\"departmentsCount\">0</h3>\r\n");
      out.write("            <span class=\"text-success\">Academic divisions</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modules -->\r\n");
      out.write("      <h4 class=\"fw-bold mb-3\">System Modules</h4>\r\n");
      out.write("      <p class=\"text-muted\">Access different areas of the school management system</p>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row g-3\">\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <div class=\"card-module bg-dark\">\r\n");
      out.write("            <i class=\"bi bi-people fs-2 text-primary\"></i>\r\n");
      out.write("            <h5 class=\"mt-3\">Students</h5>\r\n");
      out.write("            <p>Manage student records, enrollment, and academic information</p>\r\n");
      out.write("            <a href=\"Students.jsp\" class=\"btn btn-outline-primary btn-sm\">Manage Students</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <div class=\"card-module bg-dark\">\r\n");
      out.write("            <i class=\"bi bi-person-badge fs-2 text-success\"></i>\r\n");
      out.write("            <h5 class=\"mt-3\">Teachers</h5>\r\n");
      out.write("            <p>Manage faculty information, assignments, and qualifications</p>\r\n");
      out.write("            <a href=\"Teachers.jsp\" class=\"btn btn-outline-success btn-sm\">Manage Teachers</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <div class=\"card-module bg-dark\">\r\n");
      out.write("            <i class=\"bi bi-journal-bookmark fs-2 text-purple\"></i>\r\n");
      out.write("            <h5 class=\"mt-3\">Courses</h5>\r\n");
      out.write("            <p>Define and manage academic courses and curriculum</p>\r\n");
      out.write("            <a href=\"Courses.jsp\" class=\"btn btn-outline-secondary btn-sm\">Manage Courses</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <div class=\"card-module bg-dark\">\r\n");
      out.write("            <i class=\"bi bi-building fs-2 text-warning\"></i>\r\n");
      out.write("            <h5 class=\"mt-3\">Departments</h5>\r\n");
      out.write("            <p>Organize academic divisions and faculty assignments</p>\r\n");
      out.write("            <a href=\"departments.jsp\" class=\"btn btn-outline-warning btn-sm\">Manage Departments</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <div class=\"card-module bg-dark\">\r\n");
      out.write("            <i class=\"bi bi-award fs-2 text-danger\"></i>\r\n");
      out.write("            <h5 class=\"mt-3\">Designations</h5>\r\n");
      out.write("            <p>Manage faculty designations and job roles</p>\r\n");
      out.write("            <a href=\"Designations.jsp\" class=\"btn btn-outline-danger btn-sm\">Manage Designations</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <div class=\"card-module bg-dark\">\r\n");
      out.write("            <i class=\"bi bi-house-door fs-2 text-info\"></i>\r\n");
      out.write("            <h5 class=\"mt-3\">Classes</h5>\r\n");
      out.write("            <p>Manage academic classes and classroom assignments</p>\r\n");
      out.write("            <a href=\"classes.jsp\" class=\"btn btn-outline-info btn-sm\">Manage Classes</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <div class=\"card-module bg-dark \">\r\n");
      out.write("            <i class=\"bi bi-pen fs-2 text-success\"></i>\r\n");
      out.write("            <h5 class=\"mt-3\">Exam Types</h5>\r\n");
      out.write("            <p>Define and manage academic exam categories</p>\r\n");
      out.write("            <a href=\"ExamTypes.jsp\" class=\"btn btn-outline-info btn-sm\">Manage Exam Types â</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <div class=\"card-module bg-dark \">\r\n");
      out.write("            <i class=\"bi bi-currency-rupee fs-2 text-warning\"></i>\r\n");
      out.write("            <h5 class=\"mt-3\">Fee Types</h5>\r\n");
      out.write("            <p>Set up and organize student fee categories</p>\r\n");
      out.write("            <a href=\"FeeTypes.jsp\" class=\"btn btn-outline-info btn-sm\">Manage Fee Type</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <div class=\"card-module bg-dark\">\r\n");
      out.write("            <i class=\"bi bi-journal-bookmark fs-2 text-purple\"></i>\r\n");
      out.write("            <h5 class=\"mt-3\">Subjects</h5>\r\n");
      out.write("            <p>Manage academic subjects and course topics</p>\r\n");
      out.write("            <a href=\"Subjects.jsp\" class=\"btn btn-outline-info btn-sm\">Manage Subjects</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <div class=\"card-module bg-dark\">\r\n");
      out.write("            <i class=\"bi bi-person-check fs-2 text-info\"></i> User Roles\r\n");
      out.write("            <h5 class=\"mt-3\">User Roles</h5>\r\n");
      out.write("            <p>Assign system roles and access permissions</p>\r\n");
      out.write("            <a href=\"userRoles.jsp\" class=\"btn btn-outline-info btn-sm\">Manage User Roles</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    fetchDashboardCounts();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function fetchDashboardCounts(){\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: 'dashboardCounts',\r\n");
      out.write("        type: 'GET',\r\n");
      out.write("        dataType: 'json',\r\n");
      out.write("        success: function(data){\r\n");
      out.write("            if(data.error){\r\n");
      out.write("                console.log(data.error);\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\"#studentsCount\").text(data.students);\r\n");
      out.write("                $(\"#teachersCount\").text(data.teachers);\r\n");
      out.write("                $(\"#coursesCount\").text(data.courses);\r\n");
      out.write("                $(\"#departmentsCount\").text(data.departments);\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("        error: function(){\r\n");
      out.write("            console.log(\"Failed to fetch dashboard counts\");\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
