/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-01-02 09:35:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class info_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"path/to/your/custom-styles.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".modal-content {\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-group {\r\n");
      out.write("	margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-group label {\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-group input, .input-group select, .input-group textarea {\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio-container input {\r\n");
      out.write("	margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".msgError {\r\n");
      out.write("	color: red;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-close {\r\n");
      out.write("	color: #6c757d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container-fluid {\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"modal fade show\" id=\"newTask\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"newTaskLabel\" aria-modal=\"true\" role=\"dialog\"\r\n");
      out.write("		style=\"display: block; padding-left: 0px;\">\r\n");
      out.write("		<div class=\"modal-dialog  modal-xl modal-dialog-centered\"\r\n");
      out.write("			role=\"document\">\r\n");
      out.write("			<div class=\"modal-content model-content-css\">\r\n");
      out.write("				<!--Header-->\r\n");
      out.write("				<div class=\"modal-header p-2\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"newTaskLabel\">Add Item</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close text-dark\"\r\n");
      out.write("						data-bs-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">×</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!--Body-->\r\n");
      out.write("				<div class=\"modal-body p-0\">\r\n");
      out.write("					<div class=\"container-fluid\">\r\n");
      out.write("						<div class=\"card\">\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<div class=\"row\">\r\n");
      out.write("									<div class=\"col-lg-12 col-md-12\">\r\n");
      out.write("										<form name=\"taskform\" method=\"post\" id=\"Item_formId\"\r\n");
      out.write("											onsubmit=\"\" class=\"is-filled\">\r\n");
      out.write("											<input type=\"hidden\" name=\"actionType\" id=\"action_type_id\"\r\n");
      out.write("												value=\"add_item\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("												<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("													<div class=\"input-group input-group-static mb-1\">\r\n");
      out.write("														<label>Item Group</label> <span id=\"spanId\">*</span>\r\n");
      out.write("														<div class=\"relative-container\">\r\n");
      out.write("															<input class=\"required form-control\" type=\"text\"\r\n");
      out.write("																id=\"search_item_group_id\" placeholder=\"Select\"\r\n");
      out.write("																onclick=\"loadRequestedItemGroup(this.value)\"\r\n");
      out.write("																oninput=\"loadRequestedItemGroup(this.value)\"\r\n");
      out.write("																autocomplete=\"off\" onfocus=\"focused(this)\"\r\n");
      out.write("																onfocusout=\"defocused(this)\"> <span\r\n");
      out.write("																class=\"msgError\" id=\"msgError_search_item_group_id\"></span>\r\n");
      out.write("															<select class=\"required form-control p-2\"\r\n");
      out.write("																id=\"item_group_id\" name=\"item_group\" size=\"5\"\r\n");
      out.write("																style=\"display: none;\">\r\n");
      out.write("															</select>\r\n");
      out.write("														</div>\r\n");
      out.write("														<span class=\"msgError\" id=\"msgError_item_group_id\"></span>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("													<div class=\"input-group input-group-static mb-1\">\r\n");
      out.write("														<label>Item Category</label><span id=\"spanId\">*</span>\r\n");
      out.write("														<div class=\"relative-container\">\r\n");
      out.write("															<input class=\"required form-control\" type=\"text\"\r\n");
      out.write("																name=\"uom_category\" id=\"search_item_category_id\"\r\n");
      out.write("																placeholder=\"Select\"\r\n");
      out.write("																onclick=\"loadRequestedItemCategory(this.value)\"\r\n");
      out.write("																autocomplete=\"off\" onfocus=\"focused(this)\"\r\n");
      out.write("																onfocusout=\"defocused(this)\"> <span\r\n");
      out.write("																class=\"msgError\" id=\"msgError_search_item_category_id\"></span>\r\n");
      out.write("															<select class=\"required form-control p-2\"\r\n");
      out.write("																id=\"item_category_id\" name=\"from_item_category\"\r\n");
      out.write("																onchange=\"generateCodeNew()\" size=\"5\"\r\n");
      out.write("																style=\"display: none;\">\r\n");
      out.write("															</select>\r\n");
      out.write("														</div>\r\n");
      out.write("														<span class=\"msgError\" id=\"msgError_item_category_id\"></span>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("												<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("													<div class=\"input-group input-group-static mb-1\">\r\n");
      out.write("														<label>Item Code </label> <span id=\"spanId\">*</span> <input\r\n");
      out.write("															type=\"text\" class=\"required form-control\"\r\n");
      out.write("															id=\"item_code_id\" name=\"item_code\" readonly=\"\"\r\n");
      out.write("															onfocus=\"focused(this)\" onfocusout=\"defocused(this)\">\r\n");
      out.write("														<span class=\"msgError\" id=\"msgError_item_code_id\"></span>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("													<div class=\"input-group input-group-static mb-1\">\r\n");
      out.write("														<label>Item Name </label><span id=\"spanId\">*</span> <input\r\n");
      out.write("															type=\"text\" class=\"required form-control\"\r\n");
      out.write("															id=\"item_name_id\" name=\"item_name\"\r\n");
      out.write("															placeholder=\"Enter Item Name\" onfocus=\"focused(this)\"\r\n");
      out.write("															onfocusout=\"defocused(this)\"> <span\r\n");
      out.write("															class=\"msgError\" id=\"msgError_item_name_id\"></span>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-md-12 col-sm-12\">\r\n");
      out.write("													<div class=\"input-group input-group-static mb-1\">\r\n");
      out.write("														<label>Item Description</label> <span id=\"spanId\">*</span>\r\n");
      out.write("														<textarea type=\"text\" rows=\"2\"\r\n");
      out.write("															class=\"required form-control\" id=\"item_description_id\"\r\n");
      out.write("															name=\"item_description\"\r\n");
      out.write("															placeholder=\"Enter Item Description\"></textarea>\r\n");
      out.write("														<span class=\"msgError\" id=\"msgError_item_description_id\"></span>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("													<div class=\"input-group input-group-static mb-1\">\r\n");
      out.write("														<label>Brand Name</label><span id=\"spanId\">*</span> <input\r\n");
      out.write("															class=\"required form-control\" type=\"text\"\r\n");
      out.write("															id=\"search_brand_id\"\r\n");
      out.write("															onclick=\"loadRequestedBrand(this.value)\"\r\n");
      out.write("															oninput=\"loadRequestedBrand(this.value)\"\r\n");
      out.write("															placeholder=\"Select\" autocomplete=\"off\"\r\n");
      out.write("															onfocus=\"focused(this)\" onfocusout=\"defocused(this)\">\r\n");
      out.write("														<span class=\"msgError\" id=\"msgError_search_brand_id\"></span>\r\n");
      out.write("														<select class=\"required form-control p-2\" id=\"brand_id\"\r\n");
      out.write("															name=\"brand\" size=\"5\" style=\"display: none;\">\r\n");
      out.write("														</select>\r\n");
      out.write("													</div>\r\n");
      out.write("													<span class=\"msgError\" id=\"msgError_brand_id\"></span>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("													<div class=\"input-group input-group-static mb-1\">\r\n");
      out.write("														<label>Model No.</label> <input type=\"text\"\r\n");
      out.write("															class=\"form-control\" id=\"model_no_id\"\r\n");
      out.write("															placeholder=\"Enter Model No.\" onfocus=\"focused(this)\"\r\n");
      out.write("															onfocusout=\"defocused(this)\"> <span\r\n");
      out.write("															class=\"msgError\" id=\"msgError_model_no_id\"></span>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("													<div class=\"input-group input-group-static mb-1\">\r\n");
      out.write("														<label>HSN Code</label><span id=\"spanId\">*</span> <input\r\n");
      out.write("															type=\"text\" class=\"required form-control\"\r\n");
      out.write("															id=\"hsn_code_id\" placeholder=\"Enter HSN Code\"\r\n");
      out.write("															onfocus=\"focused(this)\" onfocusout=\"defocused(this)\">\r\n");
      out.write("														<span class=\"msgError\" id=\"msgError_hsn_code_id\"></span>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("													<div class=\"input-group input-group-static mb-1\">\r\n");
      out.write("														<label>Size</label> <input type=\"text\"\r\n");
      out.write("															class=\"form-control\" id=\"size_id\"\r\n");
      out.write("															placeholder=\"Enter Size\" onfocus=\"focused(this)\"\r\n");
      out.write("															onfocusout=\"defocused(this)\"> <span\r\n");
      out.write("															class=\"msgError\" id=\"msgError_size_id\"></span>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("													<div class=\"input-group input-group-static mb-1\">\r\n");
      out.write("														<label>Warranty</label> <input type=\"text\"\r\n");
      out.write("															class=\"form-control\" id=\"warranty_id\"\r\n");
      out.write("															placeholder=\"Enter Warranty\" onfocus=\"focused(this)\"\r\n");
      out.write("															onfocusout=\"defocused(this)\"> <span\r\n");
      out.write("															class=\"msgError\" id=\"msgError_warranty_id\"></span>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("													<div class=\"input-group input-group-static mb-1\">\r\n");
      out.write("														<label>Uom name</label> <span id=\"spanId\">*</span>\r\n");
      out.write("														<div class=\"relative-container\">\r\n");
      out.write("															<input class=\"required form-control\" type=\"text\"\r\n");
      out.write("																placeholder=\"Select\" id=\"search_uom_id\"\r\n");
      out.write("																onclick=\"loadRequestedUomNames(this.value)\"\r\n");
      out.write("																oninput=\"loadRequestedUomNames(this.value)\"\r\n");
      out.write("																autocomplete=\"off\" onfocus=\"focused(this)\"\r\n");
      out.write("																onfocusout=\"defocused(this)\"> <span\r\n");
      out.write("																class=\"msgError\" id=\"msgError_search_uom_id\"></span> <select\r\n");
      out.write("																class=\"required form-control p-2\" id=\"uom_id\" name=\"uom\"\r\n");
      out.write("																size=\"5\" style=\"display: none;\">\r\n");
      out.write("															</select>\r\n");
      out.write("														</div>\r\n");
      out.write("														<span class=\"msgError\" id=\"msgError_uom_id\"></span>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("													<div class=\"input-group input-group-static mb-1\">\r\n");
      out.write("														<label>Per Unit Price</label><span id=\"spanId\">*</span> <input\r\n");
      out.write("															class=\"required form-control\" type=\"text\"\r\n");
      out.write("															id=\"per_unit_price\" placeholder=\"Enter Per Unit Price\"\r\n");
      out.write("															onfocus=\"focused(this)\" onfocusout=\"defocused(this)\">\r\n");
      out.write("														<span class=\"msgError\" id=\"msgError_per_unit_price\"></span>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("													<div class=\"input-group input-group-static mb-1\">\r\n");
      out.write("														<label>Is Active</label>\r\n");
      out.write("														<div class=\"radio-container is-filled\">\r\n");
      out.write("															<input type=\"radio\" id=\"yes\" name=\"is_active_option\"\r\n");
      out.write("																value=\"1\" checked=\"\"> <label class=\"radio-label\"\r\n");
      out.write("																for=\"yes\">Yes</label> <input type=\"radio\" id=\"no\"\r\n");
      out.write("																name=\"is_active_option\" value=\"0\"> <label\r\n");
      out.write("																class=\"radio-label\" for=\"no\">No</label>\r\n");
      out.write("														</div>\r\n");
      out.write("														<span class=\"msgError\" id=\"msgError_is_active_id\"></span>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("													<div class=\"input-group input-group-static mb-4\">\r\n");
      out.write("														<label>Assignee type </label><span id=\"spanId\">*</span>\r\n");
      out.write("														<div class=\"radio-container is-filled\">\r\n");
      out.write("															<input type=\"radio\" id=\"group\" name=\"assignee_type\"\r\n");
      out.write("																value=\"1\" onchange=\"toggleAssigneeSection(this)\"\r\n");
      out.write("																class=\"radio-input\">&nbsp;&nbsp; <label\r\n");
      out.write("																class=\"radio-label\" for=\"group\">Group</label> <input\r\n");
      out.write("																type=\"radio\" id=\"user\" name=\"assignee_type\" value=\"0\"\r\n");
      out.write("																onchange=\"toggleAssigneeSection(this)\"\r\n");
      out.write("																class=\"radio-input\" checked=\"\">&nbsp;&nbsp; <label\r\n");
      out.write("																class=\"radio-label\" for=\"user\">User</label>\r\n");
      out.write("														</div>\r\n");
      out.write("														<span class=\"msgError\" id=\"msgError_assignee_type\"></span>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("													<div class=\"input-group input-group-static mb-4\"\r\n");
      out.write("														id=\"assigneeGroupSection\" style=\"display: none;\">\r\n");
      out.write("														<label>Approval</label><span id=\"spanId\">*</span>\r\n");
      out.write("														<div class=\"relative-container\">\r\n");
      out.write("															<input class=\"form-control required\" type=\"text\"\r\n");
      out.write("																id=\"search_employee_group_id\"\r\n");
      out.write("																onclick=\"loadAssigneeToGroup(this.value)\"\r\n");
      out.write("																placeholder=\"Select Employee Group Name\"\r\n");
      out.write("																autocomplete=\"off\" onfocus=\"focused(this)\"\r\n");
      out.write("																onfocusout=\"defocused(this)\"> <span\r\n");
      out.write("																class=\"msgError\" id=\"msgError_search_employee_group_id\"></span>\r\n");
      out.write("															<select class=\"form-control required p-2\"\r\n");
      out.write("																id=\"employee_group_id\" name=\"employee_group\" size=\"5\"\r\n");
      out.write("																style=\"display: none; background-color: white;\"></select>\r\n");
      out.write("														</div>\r\n");
      out.write("														<span class=\"msgError\" id=\"msgError_employee_group_id\"></span>\r\n");
      out.write("													</div>\r\n");
      out.write("\r\n");
      out.write("													<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("														<div class=\"input-group input-group-static mb-4\"\r\n");
      out.write("															id=\"assigneeUserSection\" style=\"display: block;\">\r\n");
      out.write("															<label>Approval</label><span id=\"spanId\">*</span>\r\n");
      out.write("															<div class=\"relative-container\">\r\n");
      out.write("																<input class=\"form-control required\" type=\"text\"\r\n");
      out.write("																	id=\"search_emp_name_id\"\r\n");
      out.write("																	onclick=\"loadAssigneeTo(this.value)\"\r\n");
      out.write("																	placeholder=\"Select Employee  Name\" autocomplete=\"off\"\r\n");
      out.write("																	onfocus=\"focused(this)\" onfocusout=\"defocused(this)\">\r\n");
      out.write("																<span class=\"msgError\" id=\"msgError_search_emp_name_id\"></span>\r\n");
      out.write("																<select class=\"form-control required p-2\"\r\n");
      out.write("																	id=\"employee_id\" name=\"employee\" size=\"5\"\r\n");
      out.write("																	style=\"display: none; background-color: white;\"></select>\r\n");
      out.write("															</div>\r\n");
      out.write("															<span class=\"msgError\" id=\"msgError_employee_id\"></span>\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("											<div class=\"row justify-content-md-end mt-2\">\r\n");
      out.write("												<div class=\"col-md-auto text-end px-1\">\r\n");
      out.write("													<button type=\"button\" class=\"btn bg-gradient-info\"\r\n");
      out.write("														id=\"taskactionid\" onclick=\"addNewItem()\">Save</button>\r\n");
      out.write("													<button type=\"button\" class=\"btn btn-link ml-auto\"\r\n");
      out.write("														data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</form>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
