/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2026-02-17 07:00:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.globecreater.dto.UserDTO;

public final class inventory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/pages/session-expire-check.jsp", Long.valueOf(1741156723510L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.globecreater.dto.UserDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write('\r');
      out.write('\n');

UserDTO userDTO = (UserDTO)session.getAttribute("loggedInUser");
if(userDTO == null){
	System.out.println("Invalid session");
	response.sendRedirect(request.getContextPath()+ "/pages/sign-in.jsp");
	return;
}

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"76x76\"\r\n");
      out.write("	href=\"../assets/img/apple-icon.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"../assets/img/favicon.png\">\r\n");
      out.write("<title>Inventory Management System | Dashboard</title>\r\n");
      out.write("<!--     Fonts and icons     -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700,900\" />\r\n");
      out.write("<!-- Nucleo Icons -->\r\n");
      out.write("<link href=\"../assets/css/nucleo-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"../assets/css/nucleo-svg.css\" rel=\"stylesheet\" />\r\n");
      out.write("<!-- Font Awesome Icons -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/42d5adcbca.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/icon?family=Material+Icons+Round\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- Material Icons -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0\" />\r\n");
      out.write("<!-- CSS Files -->\r\n");
      out.write("<link id=\"pagestyle\" href=\"../assets/css/material-dashboard.css?v=3.2.0\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"g-sidenav-show  bg-gray-100\">\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "left-nav.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<main\r\n");
      out.write("		class=\"main-content position-relative max-height-vh-100 h-100 border-radius-lg \">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container-fluid py-2\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"ms-3\">\r\n");
      out.write("					<h3 class=\"mb-0 h4 font-weight-bolder\">Inventory</h3>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"card-body\">\r\n");
      out.write("				<div class=\"content p-3\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-md-3\">\r\n");
      out.write("							<span class=\"section-heading\"><i\r\n");
      out.write("								class=\"material-icons-round text-sm\">apps</i> Items Catalogue</span>\r\n");
      out.write("							<ul class=\"list-item mt-2\">\r\n");
      out.write("								<li><a href=\"items.jsp\" class=\"text-sm\">Items <i\r\n");
      out.write("										class=\"material-icons-round text-sm\">north_east</i></a></li>\r\n");
      out.write("								<li><a href=\"item-group.jsp\" class=\"text-sm\">Item Group\r\n");
      out.write("										<i class=\"material-icons-round text-sm\">north_east</i>\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li><a href=\"item_category.jsp\" class=\"text-sm\">Item\r\n");
      out.write("										Category <i class=\"material-icons-round text-sm\">north_east</i>\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li><a href=\"brand.jsp\" class=\"text-sm\">Brand <i\r\n");
      out.write("										class=\"material-icons-round text-sm\">north_east</i></a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-3\">\r\n");
      out.write("							<span class=\"section-heading\"><i\r\n");
      out.write("								class=\"material-icons-round text-sm\">settings</i> Settings</span>\r\n");
      out.write("							<ul class=\"list-item mt-2\">\r\n");
      out.write("								<li><a href=\"uom.jsp\" class=\"text-sm\">UOM <i\r\n");
      out.write("										class=\"material-icons-round text-sm\">north_east</i></a></li>\r\n");
      out.write("								<li><a href=\"warehouse.jsp\" class=\"text-sm\">Warehouse <i\r\n");
      out.write("										class=\"material-icons-round text-sm\">north_east</i></a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-3\">\r\n");
      out.write("							<span class=\"section-heading\"><i\r\n");
      out.write("								class=\"material-icons-round text-sm\">description</i> Stock\r\n");
      out.write("								Transactions</span>\r\n");
      out.write("							<ul class=\"list-item mt-2\">\r\n");
      out.write("								<li><a href=\"stock_material_request.jsp\" class=\"text-sm\">Material\r\n");
      out.write("										Request <i class=\"material-icons-round text-sm\">north_east</i>\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li><a href=\"stock_entry.jsp\" class=\"text-sm\">Stock\r\n");
      out.write("										Entry <i class=\"material-icons-round text-sm\">north_east</i>\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li><a href=\"purchase_order.jsp\" class=\"text-sm\">Purchase\r\n");
      out.write("										Order <i class=\"material-icons-round text-sm\">north_east</i>\r\n");
      out.write("								</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-3\">\r\n");
      out.write("							<span class=\"section-heading\"><i\r\n");
      out.write("								class=\"material-icons-round text-sm\">summarize</i> Supplier</span>\r\n");
      out.write("							<ul class=\"list-item mt-2\">\r\n");
      out.write("								<li><a href=\"supplier.jsp\" class=\"text-sm\">Supplier <i\r\n");
      out.write("										class=\"material-icons-round text-sm\">north_east</i></a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("	</main>\r\n");
      out.write("	<!--   Core JS Files   -->\r\n");
      out.write("	<script src=\"../assets/js/core/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"../assets/js/core/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"../assets/js/plugins/perfect-scrollbar.min.js\"></script>\r\n");
      out.write("	<script src=\"../assets/js/plugins/smooth-scrollbar.min.js\"></script>\r\n");
      out.write("	<script src=\"../assets/js/plugins/chartjs.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Github buttons -->\r\n");
      out.write("	<script async defer src=\"https://buttons.github.io/buttons.js\"></script>\r\n");
      out.write("	<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->\r\n");
      out.write("	<script src=\"../assets/js/material-dashboard.min.js?v=3.2.0\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
