/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-03-05 06:40:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.globecreater.dto.UserDTO;

public final class item_002dgroup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/pages/session-expire-check.jsp", Long.valueOf(1741156723510L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.globecreater.dto.UserDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write('\r');
      out.write('\n');

UserDTO userDTO = (UserDTO)session.getAttribute("loggedInUser");
if(userDTO == null){
	System.out.println("Invalid session");
	response.sendRedirect(request.getContextPath()+ "/pages/sign-in.jsp");
	return;
}

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"76x76\"\r\n");
      out.write("	href=\"../assets/img/apple-icon.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"../assets/img/favicon.png\">\r\n");
      out.write("<title>Inventory Management System | Dashboard</title>\r\n");
      out.write("<!--     Fonts and icons     -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700,900\" />\r\n");
      out.write("<!-- Nucleo Icons -->\r\n");
      out.write("<link href=\"../assets/css/nucleo-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"../assets/css/nucleo-svg.css\" rel=\"stylesheet\" />\r\n");
      out.write("<!-- Font Awesome Icons -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/42d5adcbca.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/icon?family=Material+Icons+Round\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- Material Icons -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0\" />\r\n");
      out.write("<!-- CSS Files -->\r\n");
      out.write("<link id=\"pagestyle\" href=\"../assets/css/material-dashboard.css?v=3.2.0\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"g-sidenav-show  bg-gray-100\">\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "left-nav.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<main\r\n");
      out.write("		class=\"main-content position-relative max-height-vh-100 h-100 border-radius-lg ps\">\r\n");
      out.write("		<!-- Navbar -->\r\n");
      out.write("		<nav\r\n");
      out.write("			class=\"navbar navbar-main navbar-expand-lg position-sticky px-0 shadow-none border-radius-xl z-index-sticky\"\r\n");
      out.write("			id=\"navbarBlur\" data-scroll=\"true\">\r\n");
      out.write("			<div class=\"container-fluid py-1 px-3\"\r\n");
      out.write("				style=\"display: block !important\">\r\n");
      out.write("				<nav aria-label=\"breadcrumb\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-6\">\r\n");
      out.write("							<ol class=\"breadcrumb\">\r\n");
      out.write("								<li class=\"breadcrumb-item\"><a i=\"\"\r\n");
      out.write("									class=\"material-icons fixed-plugin-button-nav cursor-pointer \"\r\n");
      out.write("									href=\"workspace.jsp\"> home </a></li>\r\n");
      out.write("								<h6 class=\"font-weight-bolder mb-0 breadcrumb-item active\">\r\n");
      out.write("									<a href=\"stock.jsp\">Materials</a>\r\n");
      out.write("								</h6>\r\n");
      out.write("								<h6 class=\"font-weight-bolder mb-0 breadcrumb-item active\">Item\r\n");
      out.write("									Group</h6>\r\n");
      out.write("							</ol>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!--End Navbar -->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"card-body p-2 height-auto\">\r\n");
      out.write("			<div class=\"container-fluid py-1\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-3\">\r\n");
      out.write("						<div class=\"input-group input-group-dynamic\">\r\n");
      out.write("							<input class=\"multisteps-form__input form-control\" type=\"text\"\r\n");
      out.write("								placeholder=\"Search Item Group ...\" name=\"searchItemGroup\"\r\n");
      out.write("								id=\"searchItemGroup\" onfocus=\"focused(this)\"\r\n");
      out.write("								onfocusout=\"defocused(this)\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-2\">\r\n");
      out.write("						<button class=\"btn btn-icon btn-2 btn-dark\" id=\"itemGroup_search\"\r\n");
      out.write("							type=\"button\">\r\n");
      out.write("							<span class=\"btn-inner--icon\"><i class=\"material-icons\">search</i></span>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-4\"></div>\r\n");
      out.write("					<div class=\"col-3\" id=\"addbtbn\" style=\"text-align: end\">\r\n");
      out.write("						<button data-bs-toggle=\"modal\" data-bs-target=\"#newTask\"\r\n");
      out.write("							onclick=\"showNewTaskModel()\"\r\n");
      out.write("							class=\"btn btn-link text-info border-0\"\r\n");
      out.write("							data-bs-placement=\"bottom\" data-bs-original-title=\"Item Group\">\r\n");
      out.write("							<i class=\"bi bi-box\"></i> Item Group\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"card-body p-2 height-auto\">\r\n");
      out.write("			<div class=\"container-fluid py-1\">\r\n");
      out.write("\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"table-responsive d-none d-md-block d-sm-none d-lg-block d-xl-block\">\r\n");
      out.write("					<table class=\"table task_table\" id=\"mytasktableId\">\r\n");
      out.write("						<thead class=\"task_table_head\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>Actions</th>\r\n");
      out.write("								<th>Company_ID</th>\r\n");
      out.write("								<th>Item_group_name</th>\r\n");
      out.write("								<th>Is Active</th>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("						<tbody id=\"myItemstbodyId\">\r\n");
      out.write("\r\n");
      out.write("						</tbody>\r\n");
      out.write("\r\n");
      out.write("					</table>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Modal For Add New Leave-->\r\n");
      out.write("		<div class=\"modal fade\" id=\"newTask\" tabindex=\"-1\"\r\n");
      out.write("			aria-labelledby=\"newTaskLabel\" style=\"display: none;\"\r\n");
      out.write("			aria-hidden=\"true\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"modal-dialog modal-dialog-scrollable  modal-lg modal-dialog-centered\"\r\n");
      out.write("				role=\"document\">\r\n");
      out.write("				<div class=\"modal-content model-content-css\">\r\n");
      out.write("					<!--Header-->\r\n");
      out.write("					<div class=\"modal-header p-2\">\r\n");
      out.write("						<h5 class=\"modal-title\" id=\"newTaskLabel\">Add Item Group</h5>\r\n");
      out.write("						<button type=\"button\" class=\"btn-close text-dark\"\r\n");
      out.write("							data-bs-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("							<span aria-hidden=\"true\">×</span>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!--Body-->\r\n");
      out.write("\r\n");
      out.write("					<div class=\"modal-body p-0\">\r\n");
      out.write("						<div class=\"container-fluid\">\r\n");
      out.write("							<div class=\"card\">\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<div class=\"row\">\r\n");
      out.write("										<div class=\"col-lg-12 col-md-12\">\r\n");
      out.write("											<form name=\"taskform\" method=\"post\" id=\"item_groupformId\"\r\n");
      out.write("												onsubmit=\"\" class=\"is-filled\">\r\n");
      out.write("\r\n");
      out.write("												<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("													<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("														<div class=\"input-group input-group-static mb-4\">\r\n");
      out.write("															<label>Item_group_name </label> <span id=\"spanId\">*</span>\r\n");
      out.write("															<input type=\"text\" class=\"required form-control\"\r\n");
      out.write("																id=\"item_group_name\" name=\"item_group_name\"\r\n");
      out.write("																placeholder=\"Enter Item Group name\"\r\n");
      out.write("																onfocus=\"focused(this)\" onfocusout=\"defocused(this)\">\r\n");
      out.write("															<span class=\"msgError\" id=\"msgError_item_group_code_id\"></span>\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("											</form>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<div class=\"row justify-content-md-end mt-4\">\r\n");
      out.write("											<div class=\"col-md-auto text-end px-1\">\r\n");
      out.write("												<button type=\"button\" class=\"btn bg-gradient-info\"\r\n");
      out.write("													id=\"taskactionid\" onclick=\"addNewItemGroup()\">Save</button>\r\n");
      out.write("												<button type=\"button\" class=\"btn btn-link ml-auto\"\r\n");
      out.write("													data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Modal -->\r\n");
      out.write("		<div class=\"modal fade\" id=\"deleteModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("			aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"modal-dialog modal-dialog-scrollable modal-dialog-centered\"\r\n");
      out.write("				role=\"document\">\r\n");
      out.write("				<div class=\"modal-content\">\r\n");
      out.write("					<div class=\"modal-header\">\r\n");
      out.write("						<h5 class=\"modal-title font-weight-normal\" id=\"deleteModalLabel\">Delete\r\n");
      out.write("							Confirmation</h5>\r\n");
      out.write("						<button type=\"button\" class=\"btn-close text-dark\"\r\n");
      out.write("							data-bs-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("							<span aria-hidden=\"true\">×</span>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-body\">Are you sure you want to delete this\r\n");
      out.write("						item?</div>\r\n");
      out.write("					<div class=\"modal-footer\">\r\n");
      out.write("						<button type=\"button\" class=\"btn bg-gradient-secondary\"\r\n");
      out.write("							data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("						<button type=\"button\" class=\"btn bg-gradient-primary\"\r\n");
      out.write("							data-bs-dismiss=\"modal\" onclick=\"deleteItemById();\">Delete</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Modal For Edit Item Group -->\r\n");
      out.write("		<div class=\"modal fade\" id=\"editTask\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("			aria-labelledby=\"editTaskLabel\" aria-hidden=\"true\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"modal-dialog modal-dialog-scrollable modal-lg modal-dialog-centered\"\r\n");
      out.write("				role=\"document\">\r\n");
      out.write("				<div class=\"modal-content model-content-css\">\r\n");
      out.write("					<!--Header-->\r\n");
      out.write("					<div class=\"modal-header p-2\">\r\n");
      out.write("						<h5 class=\"modal-title\" id=\"editTaskLabel\">Edit Item Group</h5>\r\n");
      out.write("						<button type=\"button\" class=\"btn-close text-dark\"\r\n");
      out.write("							data-bs-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("							<span aria-hidden=\"true\">×</span>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!--Body-->\r\n");
      out.write("					<div class=\"modal-body p-0\">\r\n");
      out.write("						<div class=\"container-fluid\">\r\n");
      out.write("							<div class=\"card\">\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<div class=\"row\">\r\n");
      out.write("										<div class=\"col-lg-12 col-md-12\">\r\n");
      out.write("											<form name=\"edittaskform\" method=\"post\"\r\n");
      out.write("												id=\"edit_item_group_form_id\" onsubmit=\"return false;\"\r\n");
      out.write("												class=\"is-filled\">\r\n");
      out.write("												<input type=\"hidden\" name=\"actionType\"\r\n");
      out.write("													id=\"edit_action_type_id\" value=\"edit_item_group\"> <input\r\n");
      out.write("													type=\"hidden\" name=\"userId\" id=\"edit_user_id\" value=\"1\">\r\n");
      out.write("												<input type=\"hidden\" name=\"userName\" value=\"ADMIN\">\r\n");
      out.write("												<input type=\"hidden\" name=\"employeeCode\"\r\n");
      out.write("													id=\"edit_employeeCode\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("												<div class=\"row\">\r\n");
      out.write("													<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("														<div class=\"input-group input-group-static mb-4\">\r\n");
      out.write("															<label>Item Group Name</label><span id=\"spanId\">*</span>\r\n");
      out.write("															<input type=\"text\" class=\"required form-control\"\r\n");
      out.write("																id=\"edit_item_group_name_id\" name=\"item_group_name\"\r\n");
      out.write("																placeholder=\"Enter item Group Name\"\r\n");
      out.write("																onfocus=\"focused(this)\" onfocusout=\"defocused(this)\">\r\n");
      out.write("															<span class=\"msgError\"\r\n");
      out.write("																id=\"msgError_edit_item_group_name_id\"></span>\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("														<div class=\"input-group input-group-static mb-4\">\r\n");
      out.write("															<label>Item Group Code</label><span id=\"spanId\">*</span>\r\n");
      out.write("															<input type=\"text\" class=\"required form-control\"\r\n");
      out.write("																id=\"edit_item_group_code_id\" name=\"item_group_code\"\r\n");
      out.write("																placeholder=\"Enter Item Group code\"\r\n");
      out.write("																onfocus=\"focused(this)\" onfocusout=\"defocused(this)\">\r\n");
      out.write("															<span class=\"msgError\"\r\n");
      out.write("																id=\"msgError_edit_item_group_code_id\"></span>\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"row\">\r\n");
      out.write("													<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("														<div class=\"input-group input-group-static mb-4\">\r\n");
      out.write("															<label>Is Active</label>\r\n");
      out.write("															<div class=\"radio-container is-filled\">\r\n");
      out.write("																<input type=\"radio\" id=\"yes\"\r\n");
      out.write("																	name=\"edit_is_active_option\" value=\"1\"> <label\r\n");
      out.write("																	class=\"radio-label\" for=\"yes\">Yes</label> <input\r\n");
      out.write("																	type=\"radio\" id=\"no\" name=\"edit_is_active_option\"\r\n");
      out.write("																	value=\"0\"> <label class=\"radio-label\" for=\"no\">No</label>\r\n");
      out.write("															</div>\r\n");
      out.write("															<span class=\"msgError\" id=\"msgError_edit_is_active_id\"></span>\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("												<div class=\"row justify-content-md-end mt-4\">\r\n");
      out.write("													<div class=\"col-md-auto text-end px-1\">\r\n");
      out.write("														<button type=\"button\" class=\"btn bg-gradient-info\"\r\n");
      out.write("															id=\"edit_task_action_id\" onclick=\"updateItemGroup();\"\r\n");
      out.write("															data-id=\"\">Update</button>\r\n");
      out.write("														<button type=\"button\" class=\"btn btn-link ml-auto\"\r\n");
      out.write("															data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("\r\n");
      out.write("														<button type=\"button\" class=\"btn btn-primary btn-block\"\r\n");
      out.write("															onclick=\"addNewItemGroup()\">Save</button>\r\n");
      out.write("\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</form>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"ps__rail-x\" style=\"left: 0px; bottom: 0px;\">\r\n");
      out.write("			<div class=\"ps__thumb-x\" tabindex=\"0\" style=\"left: 0px; width: 0px;\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"ps__rail-y\" style=\"top: 0px; right: 0px;\">\r\n");
      out.write("			<div class=\"ps__thumb-y\" tabindex=\"0\" style=\"top: 0px; height: 0px;\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	<!--   Core JS Files   -->\r\n");
      out.write("	<script src=\"../assets/js/core/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"../assets/js/core/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"../assets/js/plugins/perfect-scrollbar.min.js\"></script>\r\n");
      out.write("	<script src=\"../assets/js/plugins/smooth-scrollbar.min.js\"></script>\r\n");
      out.write("	<script src=\"../assets/js/plugins/chartjs.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Github buttons -->\r\n");
      out.write("	<script async defer src=\"https://buttons.github.io/buttons.js\"></script>\r\n");
      out.write("	<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->\r\n");
      out.write("	<script src=\"../assets/js/material-dashboard.min.js?v=3.2.0\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function displayRecords() {\r\n");
      out.write("			console.log('Display');\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function addNewItemGroup() {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"");
      out.print(request.getContextPath());
      out.write("\r\n");
      out.write("		/items\",\r\n");
      out.write("				type : 'POST',\r\n");
      out.write("				data : {\r\n");
      out.write("					action : \"insert\",\r\n");
      out.write("					item_group_name : $(\"#item_group_name\").val()\r\n");
      out.write("				},\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					$(\"#newTask\").modal(\"hide\");\r\n");
      out.write("					displayRecords();\r\n");
      out.write("				},\r\n");
      out.write("				error : function(error) {\r\n");
      out.write("					alert(error);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
