/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-02-24 06:10:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"author\" content=\"IT Solution Hub\">\r\n");
      out.write("\r\n");
      out.write("<title>IT Solution Hub</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/42d5adcbca.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Material Dashboard CSS -->\r\n");
      out.write("<link id=\"pagestyle\" href=\"./assets/css/material-dashboard.css?v=3.0.6\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	background-image: url('image.jpg');\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-position: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"bg-gray-200\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("	\r\n");
      out.write("		<!-- Navbar -->\r\n");
      out.write("		<nav\r\n");
      out.write("			class=\"navbar navbar-expand-lg navbar-dark bg-dark position-absolute top-0 w-100 shadow my-3\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<a class=\"navbar-brand\" href=\"#\"> <img src=\"logo.jpg\"\r\n");
      out.write("					class=\"navbar-brand-img\" style=\"width: 35%\" alt=\"IT Solution Hub\">\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!-- End Navbar -->\r\n");
      out.write("\r\n");
      out.write("		<main class=\"main-content mt-5\">\r\n");
      out.write("			<div class=\"page-header align-items-start min-vh-100\"\r\n");
      out.write("				style=\"background-image: url('./assets/img/pms-banner.jpg?v=1');\">\r\n");
      out.write("				<span class=\"bg-gradient-dark\"></span>\r\n");
      out.write("				<div class=\"container my-auto\">\r\n");
      out.write("					<div class=\"row justify-content-center\">\r\n");
      out.write("						<div class=\"col-lg-4 col-md-8\">\r\n");
      out.write("							<div class=\"card z-index-0 shadow-lg\">\r\n");
      out.write("								<div\r\n");
      out.write("									class=\"card-header p-0 position-relative mt-n4 mx-3 z-index-2\">\r\n");
      out.write("									<div class=\"bg-dark text-center py-3\">\r\n");
      out.write("										<img src=\"logo.jpg\" class=\"navbar-brand-img\"\r\n");
      out.write("											style=\"width: 15%\" alt=\"IT Solution Hub\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<form role=\"form\" action=\"userlogin\" method=\"post\">\r\n");
      out.write("										<div class=\"mb-4\">\r\n");
      out.write("											<label for=\"email\" class=\"form-label\">Email Or Phone\r\n");
      out.write("												Number</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("												name=\"username\" id=\"email\"\r\n");
      out.write("												placeholder=\"abc@example.com /123-45-678\" required>\r\n");
      out.write("											<div class=\"text-danger mt-2\" id=\"showError\"\r\n");
      out.write("												style=\"display: none;\"></div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<div class=\"mb-4\">\r\n");
      out.write("											<label for=\"passwordId\" class=\"form-label\">Password</label> <input\r\n");
      out.write("												type=\"password\" class=\"form-control\" name=\"password\"\r\n");
      out.write("												id=\"passwordId\" placeholder=\"*************\" required>\r\n");
      out.write("											<div id=\"passErrorId\" class=\"text-danger mt-2\"\r\n");
      out.write("												style=\"display: none;\"></div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<div\r\n");
      out.write("											class=\"form-check form-switch d-flex align-items-center mb-4\">\r\n");
      out.write("											<input class=\"form-check-input\" type=\"checkbox\"\r\n");
      out.write("												id=\"rememberMe\" name=\"rememberme\" value=\"Rememberme\">\r\n");
      out.write("											<label class=\"form-check-label ms-3\" for=\"rememberMe\">Remember\r\n");
      out.write("												me</label>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<div class=\"text-center\">\r\n");
      out.write("											<button type=\"submit\" class=\"btn btn-dark w-100 mt-3 mb-0\"\r\n");
      out.write("												onclick=\"return validate()\">Sign in</button>\r\n");
      out.write("										</div>\r\n");
      out.write("									</form>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"card-footer text-center pt-0 px-lg-2 px-1\">\r\n");
      out.write("									<p class=\"mb-4 text-sm mx-auto\">\r\n");
      out.write("										Forgot password? <a href=\"forgotpassword.jsp\"\r\n");
      out.write("											class=\"text-success font-weight-bold\">Click here</a>\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</main>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		function validate() {\r\n");
      out.write("			var email = $('#email').val();\r\n");
      out.write("			var password = $('#passwordId').val();\r\n");
      out.write("\r\n");
      out.write("			if (email === '') {\r\n");
      out.write("				$(\"#showError\").text(\"Please Enter Your Email Or Phone Number\")\r\n");
      out.write("						.show();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (password === '') {\r\n");
      out.write("				$(\"#showError\").hide();\r\n");
      out.write("				$(\"#passErrorId\").text(\"Please enter password\").show();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			$(\"#passErrorId\").hide();\r\n");
      out.write("			return true;\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- <script>\r\n");
      out.write("	\r\n");
      out.write("		// Function to set cookies\r\n");
      out.write("		function setCookie(name, value, days) {\r\n");
      out.write("			var expires = \"\";\r\n");
      out.write("			if (days) {\r\n");
      out.write("				var date = new Date();\r\n");
      out.write("				date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));\r\n");
      out.write("				expires = \"; expires=\" + date.toUTCString();\r\n");
      out.write("			}\r\n");
      out.write("			document.cookie = name + \"=\" + (value || \"\") + expires + \"; path=/\";\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// Function to get cookies\r\n");
      out.write("		function getCookie(name) {\r\n");
      out.write("			var nameEQ = name + \"=\";\r\n");
      out.write("			var ca = document.cookie.split(';');\r\n");
      out.write("			for (var i = 0; i < ca.length; i++) {\r\n");
      out.write("				var c = ca[i];\r\n");
      out.write("				while (c.charAt(0) == ' ')\r\n");
      out.write("					c = c.substring(1, c.length);\r\n");
      out.write("				if (c.indexOf(nameEQ) == 0)\r\n");
      out.write("					return c.substring(nameEQ.length, c.length);\r\n");
      out.write("			}\r\n");
      out.write("			return null;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// Function to check cookies and prefill form if needed\r\n");
      out.write("		function checkCookies() {\r\n");
      out.write("			var storedEmail = getCookie('userEmail');\r\n");
      out.write("			var storedPassword = getCookie('userPassword');\r\n");
      out.write("			if (storedEmail) {\r\n");
      out.write("				$('#email').val(storedEmail);\r\n");
      out.write("			}\r\n");
      out.write("			if (storedPassword) {\r\n");
      out.write("				$('#passwordId').val(storedPassword);\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// Validate function modified to handle cookies\r\n");
      out.write("		function validate() {\r\n");
      out.write("			var email = $('#email').val();\r\n");
      out.write("			var password = $('#passwordId').val();\r\n");
      out.write("			var rememberMe = $('#rememberMe').prop('checked');\r\n");
      out.write("\r\n");
      out.write("			if (email === '') {\r\n");
      out.write("				$(\"#showError\").text(\"Please Enter Your Email Or Phone Number\")\r\n");
      out.write("						.show();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (password === '') {\r\n");
      out.write("				$(\"#showError\").hide();\r\n");
      out.write("				$(\"#passErrorId\").text(\"Please enter password\").show();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// Store email and password in cookies if \"Remember me\" is checked\r\n");
      out.write("			if (rememberMe) {\r\n");
      out.write("				setCookie('userEmail', email, 7); // Store for 7 days\r\n");
      out.write("				setCookie('userPassword', password, 7); // Store for 7 days\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			$(\"#passErrorId\").hide();\r\n");
      out.write("			return true;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// Call checkCookies when page loads to autofill if cookies are set\r\n");
      out.write("		window.onload = function() {\r\n");
      out.write("			checkCookies();\r\n");
      out.write("		}\r\n");
      out.write("	</script> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
