/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-12-11 06:45:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tableInfoBootstrap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("		<h1 style=\"text-align: center; color: green;\">Student Information</h1>\r\n");
      out.write("		<form action=\"Student\" method=\"post\">\r\n");
      out.write("			<!-- Bootstrap table class -->\r\n");
      out.write("			<table class=\"table\">\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr class=\"table-primary\">\r\n");
      out.write("						<th scope=\"col\">Id</th>\r\n");
      out.write("						<th scope=\"col\">Name</th>\r\n");
      out.write("						<th scope=\"col\">City</th>\r\n");
      out.write("						<th scope=\"col\">Age</th>\r\n");
      out.write("						<th scope=\"col\">Contact</th>\r\n");
      out.write("						<th scope=\"col\">Stream</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr class=\"table-secondary\">\r\n");
      out.write("						<td scope=\"row\">1</td>\r\n");
      out.write("						<td>Anish</td>\r\n");
      out.write("						<td>Pune</td>\r\n");
      out.write("						<td>21</td>\r\n");
      out.write("						<td>985632554</td>\r\n");
      out.write("						<td>Mechanical</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr class=\"table-success\">\r\n");
      out.write("						<td scope=\"row\">2</td>\r\n");
      out.write("						<td>Vishal</td>\r\n");
      out.write("						<td>Maharashtra</td>\r\n");
      out.write("						<td>24</td>\r\n");
      out.write("						<td>987777754</td>\r\n");
      out.write("						<td>Computer</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr class=\"table-info\">\r\n");
      out.write("						<td scope=\"row\">3</td>\r\n");
      out.write("						<td>Nikita</td>\r\n");
      out.write("						<td>Mumbai</td>\r\n");
      out.write("						<td>23</td>\r\n");
      out.write("						<td>888882554</td>\r\n");
      out.write("						<td>Computer Science</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr class=\"table-light\">\r\n");
      out.write("						<td scope=\"row\">4</td>\r\n");
      out.write("						<td>Yogesh</td>\r\n");
      out.write("						<td>Shimla</td>\r\n");
      out.write("						<td>24</td>\r\n");
      out.write("						<td>966666554</td>\r\n");
      out.write("						<td>MCA</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr class=\"table-dark\">\r\n");
      out.write("						<td scope=\"row\">5</td>\r\n");
      out.write("						<td>Shridhar</td>\r\n");
      out.write("						<td>Delhi</td>\r\n");
      out.write("						<td>25</td>\r\n");
      out.write("						<td>985555554</td>\r\n");
      out.write("						<td>Civil</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr class=\"table-active\">\r\n");
      out.write("						<td scope=\"row\">6</td>\r\n");
      out.write("						<td>Pratik</td>\r\n");
      out.write("						<td>Noida</td>\r\n");
      out.write("						<td>26</td>\r\n");
      out.write("						<td>985111114</td>\r\n");
      out.write("						<td>Mechanical</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr class=\"table-danger\">\r\n");
      out.write("						<td scope=\"row\">7</td>\r\n");
      out.write("						<td>Abdul</td>\r\n");
      out.write("						<td>Bengaluru</td>\r\n");
      out.write("						<td>27</td>\r\n");
      out.write("						<td>985333333</td>\r\n");
      out.write("						<td>MCA</td>\r\n");
      out.write("						<input type=\"submit\" class=\"btn btn-primary\" id=\"subBtn\"\r\n");
      out.write("							value=\"Register\" class=\"btn\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("			<button onclick=\"window.location.href='Student'\">servlet</button>\r\n");
      out.write("	</div>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
