/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-11-04 06:00:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1758008229897L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>MAJAD Home Page.....</title>\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- Google Material Icons -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Arial', sans-serif;\r\n");
      out.write("	background-color: #f5f5f5;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Sidebar */\r\n");
      out.write(".sidebar {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 250px;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("	background-color: #fff; /* Changed to white */\r\n");
      out.write("	border-right: 1px solid #ddd;\r\n");
      out.write("	/* Adjusted border to match white theme */\r\n");
      out.write("	padding: 24px; /* Equivalent to p-6 (24px) */\r\n");
      out.write("	overflow-y: auto;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	color: #333; /* Adjusted text color for readability on white */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .header {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	gap: 8px; /* Equivalent to gap-2 */\r\n");
      out.write("	border-bottom: 1px solid #ddd;\r\n");
      out.write("	/* Adjusted border to match white theme */\r\n");
      out.write("	padding-bottom: 24px; /* Consistent with p-6 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .header .brand {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	gap: 12px; /* Equivalent to gap-3 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .header .brand .icon {\r\n");
      out.write("	width: 48px; /* w-12 */\r\n");
      out.write("	height: 48px; /* h-12 */\r\n");
      out.write("	background: linear-gradient(to bottom right, #8B4513, #D2B48C);\r\n");
      out.write("	/* Retained homepage gradient */\r\n");
      out.write("	border-radius: 8px; /* rounded-xl */\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* shadow-lg */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .header .brand .icon .material-icons {\r\n");
      out.write("	font-size: 28px; /* w-7 h-7 equivalent */\r\n");
      out.write("	color: #d4a017; /* gold-accent, retained for contrast */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .header .brand .text h2 {\r\n");
      out.write("	font-size: 1.25rem; /* text-xl */\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	color: #333; /* Adjusted to dark text for white background */\r\n");
      out.write("	letter-spacing: 0.05em; /* tracking-wide */\r\n");
      out.write("	margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .header .brand .text p {\r\n");
      out.write("	font-size: 0.75rem; /* text-xs */\r\n");
      out.write("	color: rgba(51, 51, 51, 0.7); /* Adjusted to dark with opacity */\r\n");
      out.write("	font-weight: 500; /* font-medium */\r\n");
      out.write("	margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .header .brand .text .est {\r\n");
      out.write("	color: rgba(51, 51, 51, 0.5); /* Adjusted to dark with lower opacity */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .content {\r\n");
      out.write("	flex: 1;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	gap: 8px; /* gap-2 */\r\n");
      out.write("	overflow-y: auto;\r\n");
      out.write("	padding: 16px; /* p-4 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .content .group {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	padding: 8px; /* p-2 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .content .group-label {\r\n");
      out.write("	height: 32px; /* h-8 */\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	padding: 12px; /* px-3 py-3 */\r\n");
      out.write("	font-size: 0.75rem; /* text-xs */\r\n");
      out.write("	font-weight: 600; /* font-semibold */\r\n");
      out.write("	color: rgba(51, 51, 51, 0.8); /* Adjusted to dark with opacity */\r\n");
      out.write("	text-transform: uppercase;\r\n");
      out.write("	letter-spacing: 0.1em; /* tracking-wider */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .content .group-content {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	font-size: 0.875rem; /* text-sm */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .content .menu {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	gap: 4px; /* gap-1 */\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .content .menu-item {\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .content .menu-item a {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	gap: 8px; /* gap-2 */\r\n");
      out.write("	padding: 12px; /* px-4 py-3 */\r\n");
      out.write("	font-size: 0.875rem; /* text-sm */\r\n");
      out.write("	color: rgba(51, 51, 51, 0.8); /* Adjusted to dark with opacity */\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	border-radius: 8px; /* rounded-xl */\r\n");
      out.write("	margin-bottom: 8px; /* mb-2 */\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("	background-color: #f5f5f5; /* Light gray background */\r\n");
      out.write("	box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05); /* shadow-sm */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .content .menu-item a:hover {\r\n");
      out.write("	background-color: #e0e0e0; /* Slightly darker gray on hover */\r\n");
      out.write("	color: #333; /* Darker text on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .content .menu-item a .material-icons {\r\n");
      out.write("	font-size: 20px; /* w-5 h-5 equivalent */\r\n");
      out.write("	transition: transform 0.3s ease;\r\n");
      out.write("	background: linear-gradient(to bottom right, #8B4513, #D2B48C);\r\n");
      out.write("	/* Retained homepage gradient */\r\n");
      out.write("	-webkit-background-clip: text; /* For text fill with gradient */\r\n");
      out.write("	background-clip: text;\r\n");
      out.write("	color: transparent;\r\n");
      out.write("	/* Make the icon color transparent to show gradient */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .content .menu-item a:hover .material-icons {\r\n");
      out.write("	transform: scale(1.1); /* group-hover:scale-110 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .content .delivery-info {\r\n");
      out.write("	padding: 16px; /* px-4 py-3 */\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	gap: 12px; /* space-y-3 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .content .delivery-info .item {\r\n");
      out.write("	font-size: 0.875rem; /* text-sm */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .content .delivery-info .item .title {\r\n");
      out.write("	font-weight: 600; /* font-semibold */\r\n");
      out.write("	color: #333; /* Adjusted to dark text */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .content .delivery-info .item .desc {\r\n");
      out.write("	color: rgba(51, 51, 51, 0.7); /* Adjusted to dark with opacity */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .footer {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	gap: 8px; /* gap-2 */\r\n");
      out.write("	border-top: 1px solid #ddd; /* Adjusted border to match white theme */\r\n");
      out.write("	padding: 24px; /* p-6 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .footer .welcome {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	gap: 12px; /* gap-3 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .footer .welcome .icon {\r\n");
      out.write("	width: 40px; /* w-10 */\r\n");
      out.write("	height: 40px; /* h-10 */\r\n");
      out.write("	background: linear-gradient(to bottom right, #8B4513, #D2B48C);\r\n");
      out.write("	/* Retained homepage gradient */\r\n");
      out.write("	border-radius: 50%; /* rounded-full */\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .footer .welcome .icon .material-icons {\r\n");
      out.write("	font-size: 20px; /* w-5 h-5 */\r\n");
      out.write("	color: #fff; /* White for contrast */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .footer .welcome .text {\r\n");
      out.write("	flex: 1;\r\n");
      out.write("	min-width: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .footer .welcome .text p {\r\n");
      out.write("	font-size: 0.875rem; /* text-sm */\r\n");
      out.write("	font-weight: 600; /* font-semibold */\r\n");
      out.write("	color: #333; /* Adjusted to dark text */\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	text-overflow: ellipsis;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .footer .welcome .text .subtext {\r\n");
      out.write("	font-size: 0.75rem; /* text-xs */\r\n");
      out.write("	color: rgba(51, 51, 51, 0.7); /* Adjusted to dark with opacity */\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	text-overflow: ellipsis;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Main Content */\r\n");
      out.write(".main-content {\r\n");
      out.write("	margin-left: 250px;\r\n");
      out.write("	padding: 40px;\r\n");
      out.write("	background: linear-gradient(135deg, #8B4513, #D2B48C);\r\n");
      out.write("	color: white;\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero-section {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero-text {\r\n");
      out.write("	max-width: 40%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero-text h1 {\r\n");
      out.write("	font-size: 3rem;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero-text p {\r\n");
      out.write("	font-size: 1.1rem;\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("	opacity: 0.9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-purple {\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	color: #764ba2;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	border-radius: 50px;\r\n");
      out.write("	padding: 10px 25px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	transition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-purple:hover {\r\n");
      out.write("	background-color: #f5f5f5;\r\n");
      out.write("	color: #764ba2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero-video {\r\n");
      out.write("	width: 55%;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero-video video {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	box-shadow: 0 8px 25px rgba(0, 0, 0, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 992px) {\r\n");
      out.write("	.main-content {\r\n");
      out.write("		margin-left: 0;\r\n");
      out.write("		padding: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	.hero-section {\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		height: auto;\r\n");
      out.write("	}\r\n");
      out.write("	.hero-text {\r\n");
      out.write("		max-width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	.hero-video {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: auto;\r\n");
      out.write("	}\r\n");
      out.write("	.hero-video video {\r\n");
      out.write("		height: auto;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("    <img src=\"logo.png\" alt=\"MAJAD Logo\"> <!-- Assume logo.png in images -->\r\n");
      out.write("    <h3>MAJAD Fine Wines & Spirits Est. 2025</h3>\r\n");
      out.write("    <h4>NAVIGATION</h4>\r\n");
      out.write("    <a href=\"home.jsp\" class=\"nav-link\">Home</a>\r\n");
      out.write("    <a href=\"shop.jsp\" class=\"nav-link\">Shop</a>\r\n");
      out.write("    <a href=\"cart.jsp\" class=\"nav-link\">Cart</a>\r\n");
      out.write("    <a href=\"orders.jsp\" class=\"nav-link\">Orders</a>\r\n");
      out.write("    <h4>DELIVERY INFO</h4>\r\n");
      out.write("    <p>Free Delivery Orders over $75</p>\r\n");
      out.write("    <p>Same Day Order before 2 PM</p>\r\n");
      out.write("    <p>Service Area Within 25 miles</p>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Sidebar -->\r\n");
      out.write("	<div class=\"sidebar\">\r\n");
      out.write("		<div class=\"header\">\r\n");
      out.write("			<div class=\"brand\">\r\n");
      out.write("				<div class=\"icon\">\r\n");
      out.write("					<span class=\"material-icons\">local_dining</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"text\">\r\n");
      out.write("					<h2>MAJAD</h2>\r\n");
      out.write("					<p>Premium Wines & Spirits</p>\r\n");
      out.write("					<p class=\"est\">Est. 2025</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"content\">\r\n");
      out.write("			<div class=\"group\">\r\n");
      out.write("				<div class=\"group-label\">Navigation</div>\r\n");
      out.write("				<div class=\"group-content\">\r\n");
      out.write("					<ul class=\"menu\">\r\n");
      out.write("						<li class=\"menu-item\"><a href=\"home.jsp\"> <span\r\n");
      out.write("								class=\"material-icons\">home</span> <span>Home</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"menu-item\"><a href=\"shop.jsp\"> <span\r\n");
      out.write("								class=\"material-icons\">store</span> <span>Shop</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"menu-item\"><a href=\"cart.jsp\"> <span\r\n");
      out.write("								class=\"material-icons\">shopping_cart</span> <span>Cart</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"menu-item\"><a href=\"orders.jsp\"> <span\r\n");
      out.write("								class=\"material-icons\">receipt_long</span> <span>Orders</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"group\">\r\n");
      out.write("				<div class=\"group-label\">Delivery Info</div>\r\n");
      out.write("				<div class=\"group-content\">\r\n");
      out.write("					<div class=\"delivery-info\">\r\n");
      out.write("						<div class=\"item\">\r\n");
      out.write("							<div class=\"title\">Free Delivery</div>\r\n");
      out.write("							<div class=\"desc\">Orders over $75</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"item\">\r\n");
      out.write("							<div class=\"title\">Same Day</div>\r\n");
      out.write("							<div class=\"desc\">Order before 2 PM</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"item\">\r\n");
      out.write("							<div class=\"title\">Service Area</div>\r\n");
      out.write("							<div class=\"desc\">Within 25 miles</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer\">\r\n");
      out.write("			<div class=\"welcome\">\r\n");
      out.write("				<div class=\"icon\">\r\n");
      out.write("					<a href=\"profile.jsp\" class=\"icon\" style=\"text-decoration:none\"> <span\r\n");
      out.write("						class=\"material-icons\">person</span>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"text\">\r\n");
      out.write("					<p>Welcome</p>\r\n");
      out.write("					<p class=\"subtext\">Premium Member</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Main Content -->\r\n");
      out.write("	<div class=\"main-content\">\r\n");
      out.write("		<div class=\"hero-section\">\r\n");
      out.write("			<div class=\"hero-text\">\r\n");
      out.write("				<h1>\r\n");
      out.write("					Premium Wines & Spirits<br>Delivered to Your Door\r\n");
      out.write("				</h1>\r\n");
      out.write("				<p>Curated selection of the finest wines and premium spirits\r\n");
      out.write("					from around the world. Experience luxury with same-day delivery\r\n");
      out.write("					service.</p>\r\n");
      out.write("				<a href=\"products.jsp\"><button class=\"btn btn-purple\">Explore Collection</button></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"hero-video\">\r\n");
      out.write("				<video autoplay muted loop playsinline>\r\n");
      out.write("					<source src=\"glasspouring.mp4\" type=\"video/mp4\">\r\n");
      out.write("					Your browser does not support the video tag.\r\n");
      out.write("				</video>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Bootstrap JS -->\r\n");
      out.write("		<script\r\n");
      out.write("			src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
