/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-11-04 06:37:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import dao.ProductDAO;
import dto.ProductDTO;

public final class products_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("dto.ProductDTO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("dao.ProductDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    ProductDAO dao = new ProductDAO((java.sql.Connection)application.getAttribute("DBConnection"));
    List<ProductDTO> products = dao.getAllProducts();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Products</title>\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            /* Premium Dusky Whiskey Gradient */\r\n");
      out.write("            background: linear-gradient(135deg, #2c1810, #5c3d2e, #b08d57);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        h2, h3 {\r\n");
      out.write("            color: #fdd835;\r\n");
      out.write("            text-shadow: 1px 1px 3px rgba(0,0,0,0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* PREMIUM GLOWING PRODUCT CARD */\r\n");
      out.write("        .card {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.08);\r\n");
      out.write("            border: 1px solid rgba(255, 215, 128, 0.3);\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            backdrop-filter: blur(12px);\r\n");
      out.write("            transition: all 0.4s ease;\r\n");
      out.write("            box-shadow: 0 6px 18px rgba(0,0,0,0.6);\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        .card::before {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: -2px; left: -2px; right: -2px; bottom: -2px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            background: linear-gradient(45deg, #ffd54f, #ff8f00, #ffcc80, #b08d57);\r\n");
      out.write("            z-index: -1;\r\n");
      out.write("            filter: blur(12px);\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            transition: opacity 0.4s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .card:hover::before { opacity: 1; }\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: translateY(-12px) scale(1.03);\r\n");
      out.write("            box-shadow: 0 12px 35px rgba(255, 174, 66, 0.6);\r\n");
      out.write("            border-color: #ffd54f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Card Image Styling */\r\n");
      out.write("        .card img {\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            height: 220px;\r\n");
      out.write("            border-top-left-radius: 20px;\r\n");
      out.write("            border-top-right-radius: 20px;\r\n");
      out.write("            border-bottom: 1px solid rgba(255,215,128,0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Title & Price Highlight */\r\n");
      out.write("        .card-body h5 {\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #ffd54f;\r\n");
      out.write("            text-shadow: 0 0 8px rgba(255, 193, 7, 0.8);\r\n");
      out.write("        }\r\n");
      out.write("        .price-tag {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #ffcc80;\r\n");
      out.write("            text-shadow: 0 0 5px rgba(255, 193, 7, 0.7);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* BUTTONS */\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background: linear-gradient(45deg, #a1887f, #6d4c41);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            background: linear-gradient(45deg, #d7a46c, #5c3d2e);\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("        .btn-success {\r\n");
      out.write("            background: linear-gradient(45deg, #ffd54f, #ffb300);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            color: #2c1810;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-success:hover {\r\n");
      out.write("            background: linear-gradient(45deg, #ffca28, #ff8f00);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Add Product Card */\r\n");
      out.write("        #addProductCollapse .card {\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background: rgba(255,255,255,0.05);\r\n");
      out.write("            border: 1px solid rgba(255,215,128,0.2);\r\n");
      out.write("            backdrop-filter: blur(8px);\r\n");
      out.write("            box-shadow: 0 6px 20px rgba(0,0,0,0.5);\r\n");
      out.write("        }\r\n");
      out.write("        #addProductCollapse .form-control {\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            background: rgba(255,255,255,0.1);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        #addProductCollapse .form-control::placeholder {\r\n");
      out.write("            color: #ffd54f;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container py-4\">\r\n");
      out.write("    <h2 class=\"text-center mb-4\"> Product Management</h2>\r\n");
      out.write("\r\n");
      out.write("    <!-- Collapsible Add Product -->\r\n");
      out.write("    <div class=\"text-center mb-4\">\r\n");
      out.write("        <button class=\"btn btn-primary px-4 py-2 shadow\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#addProductCollapse\" aria-expanded=\"false\" aria-controls=\"addProductCollapse\">\r\n");
      out.write("            ➕ Add New Product\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"collapse\" id=\"addProductCollapse\">\r\n");
      out.write("        <div class=\"card card-body shadow-sm mb-5\">\r\n");
      out.write("            <form id=\"addProductFormData\" enctype=\"multipart/form-data\">\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">Product Name</label>\r\n");
      out.write("                    <input type=\"text\" name=\"name\" class=\"form-control\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">Price (₹)</label>\r\n");
      out.write("                    <input type=\"number\" name=\"price\" class=\"form-control\" step=\"0.01\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">Description</label>\r\n");
      out.write("                    <textarea name=\"description\" class=\"form-control\" rows=\"3\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">Product Image</label>\r\n");
      out.write("                    <input type=\"file\" name=\"image\" class=\"form-control\" accept=\"image/*\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"add\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-success w-100\">Save Product</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Product List -->\r\n");
      out.write("    <h3 class=\"mb-3\"> Available Products</h3>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        ");
 if(products != null && !products.isEmpty()){ 
            for(ProductDTO p : products){ 
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                    <div class=\"card h-100\">\r\n");
      out.write("                        ");
 if(p.getImageUrl() != null && !p.getImageUrl().isEmpty()){ 
      out.write("\r\n");
      out.write("                            <img src=\"");
      out.print(request.getContextPath());
      out.write('/');
      out.print( p.getImageUrl() );
      out.write("\" class=\"card-img-top\" alt=\"");
      out.print( p.getName() );
      out.write("\">\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <img src=\"https://source.unsplash.com/400x300/?whiskey,bottle\" class=\"card-img-top\" alt=\"Default Image\">\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <h5 class=\"card-title\">");
      out.print( p.getName() );
      out.write("</h5>\r\n");
      out.write("                            <p class=\"price-tag\">₹");
      out.print( p.getPrice() );
      out.write("</p>\r\n");
      out.write("                            <p class=\"card-text\">");
      out.print( p.getDescription() );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        ");
  } 
        } else { 
      out.write("\r\n");
      out.write("            <p class=\"text-light\">No products available.</p>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- JS -->\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $('#addProductFormData').submit(function(e){\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        let formData = new FormData(this);\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: '");
      out.print(request.getContextPath());
      out.write("/products',\r\n");
      out.write("            type: 'POST',\r\n");
      out.write("            data: formData,\r\n");
      out.write("            contentType: false,\r\n");
      out.write("            processData: false,\r\n");
      out.write("            success: function(response){\r\n");
      out.write("                if(response.trim()===\"success\"){\r\n");
      out.write("                    alert(\"✅ Product Added\");\r\n");
      out.write("                    location.reload();\r\n");
      out.write("                } else {\r\n");
      out.write("                    alert(\"❌ Failed to add product\");\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
