/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-02-25 05:08:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcomeCookies_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>User Login</title>\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" \r\n");
      out.write("    integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <style>\r\n");
      out.write("body {\r\n");
      out.write("	background-image: url('fullview.jpg');\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-position: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f4f6f9;\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 500px;\r\n");
      out.write("            margin-top: 50px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            color: #007BFF;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-label {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control {\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            background-color: #007BFF;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"checkCookie()\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2>User Information Form</h2>\r\n");
      out.write("        <form id=\"userForm\" onsubmit=\"event.preventDefault(); submitForm();\">\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"email\" class=\"form-label\">Email:</label>\r\n");
      out.write("                <input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"address\" class=\"form-label\">Address:</label>\r\n");
      out.write("                <input type=\"text\" id=\"address\" name=\"address\" class=\"form-control\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"phoneNumber\" class=\"form-label\">Phone Number:</label>\r\n");
      out.write("                <input type=\"text\" id=\"phoneNumber\" name=\"phoneNumber\" class=\"form-control\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"password\" class=\"form-label\">Password:</label>\r\n");
      out.write("                <input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\">Submit</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS and Popper.js -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js\" \r\n");
      out.write("    integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zyJ2t6by1mN0d5xY5BRSF1g1Gv4nJH4f7dy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js\" \r\n");
      out.write("    integrity=\"sha384-pzjw8f+ua7Kw1TIq0eLVm7bPtBkVq5qu1C1FZbK6TAcflXT2U1TkNf9JhJdy9X2k\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Cookie Script -->\r\n");
      out.write("    <script>\r\n");
      out.write("        <!--  Set a cookie with a name, value, and expiration days -->\r\n");
      out.write("        function setCookie(cname, cvalue, exdays) {\r\n");
      out.write("            const d = new Date();\r\n");
      out.write("            d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));\r\n");
      out.write("            let expires = \"expires=\" + d.toUTCString();\r\n");
      out.write("            document.cookie = cname + \"=\" + cvalue + \";\" + expires + \";path=/\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        <!-- Get the value of a cookie by its name  -->\r\n");
      out.write("        function getCookie(cname) {\r\n");
      out.write("            let name = cname + \"=\";\r\n");
      out.write("            let decodedCookie = decodeURIComponent(document.cookie);\r\n");
      out.write("            let ca = decodedCookie.split(';');\r\n");
      out.write("            for (let i = 0; i < ca.length; i++) {\r\n");
      out.write("                let c = ca[i];\r\n");
      out.write("                while (c.charAt(0) == ' ') {\r\n");
      out.write("                    c = c.substring(1);\r\n");
      out.write("                }\r\n");
      out.write("                if (c.indexOf(name) == 0) {\r\n");
      out.write("                    return c.substring(name.length, c.length);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            return \"\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        <!-- Check cookies and show user info or prompt for data  -->\r\n");
      out.write("        function checkCookie() {\r\n");
      out.write("            let username = getCookie(\"username\");\r\n");
      out.write("            let email = getCookie(\"email\");\r\n");
      out.write("            let address = getCookie(\"address\");\r\n");
      out.write("            let phoneNumber = getCookie(\"phoneNumber\");\r\n");
      out.write("            let password = getCookie(\"password\");\r\n");
      out.write("\r\n");
      out.write("            if (username != \"\") {\r\n");
      out.write("                alert(\"Welcome back \" + username);\r\n");
      out.write("            } else {\r\n");
      out.write("                username = prompt(\"Please enter your name:\", \"\");\r\n");
      out.write("                if (username != \"\" && username != null) {\r\n");
      out.write("                    setCookie(\"username\", username, 30);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            <!-- Check for other cookies and fill out form fields if available  -->\r\n");
      out.write("            if (email != \"\") {\r\n");
      out.write("                document.getElementById(\"email\").value = email;\r\n");
      out.write("            }\r\n");
      out.write("            if (address != \"\") {\r\n");
      out.write("                document.getElementById(\"address\").value = address;\r\n");
      out.write("            }\r\n");
      out.write("            if (phoneNumber != \"\") {\r\n");
      out.write("                document.getElementById(\"phoneNumber\").value = phoneNumber;\r\n");
      out.write("            }\r\n");
      out.write("            if (password != \"\") {\r\n");
      out.write("                document.getElementById(\"password\").value = password;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        <!-- Set cookies when form is submitted  -->\r\n");
      out.write("        function submitForm() {\r\n");
      out.write("            let email = document.getElementById(\"email\").value;\r\n");
      out.write("            let address = document.getElementById(\"address\").value;\r\n");
      out.write("            let phoneNumber = document.getElementById(\"phoneNumber\").value;\r\n");
      out.write("            let password = document.getElementById(\"password\").value;\r\n");
      out.write("\r\n");
      out.write("            if (email != \"\") {\r\n");
      out.write("                setCookie(\"email\", email, 30);\r\n");
      out.write("            }\r\n");
      out.write("            if (address != \"\") {\r\n");
      out.write("                setCookie(\"address\", address, 30);\r\n");
      out.write("            }\r\n");
      out.write("            if (phoneNumber != \"\") {\r\n");
      out.write("                setCookie(\"phoneNumber\", phoneNumber, 30);\r\n");
      out.write("            }\r\n");
      out.write("            if (password != \"\") {\r\n");
      out.write("                setCookie(\"password\", password, 30);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            alert(\"Form submitted and cookies are saved!\");\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
